#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Ability_101841_BP

#include "Basic.hpp"

#include "PyAbility_101841_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_101841_BP.Ability_101841_BP_C
// 0x0000 (0x25B0 - 0x25B0)
class UAbility_101841_BP_C final : public UPyAbility_101841
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_101841_BP_C">();
	}
	static class UAbility_101841_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_101841_BP_C>();
	}
};

}

