#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Ability_103392_BP

#include "Basic.hpp"

#include "Ability_ThrowBall_BP_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_103392_BP.Ability_103392_BP_C
// 0x0000 (0x25A0 - 0x25A0)
class UAbility_103392_BP_C final : public UAbility_ThrowBall_BP_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_103392_BP_C">();
	}
	static class UAbility_103392_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_103392_BP_C>();
	}
};

}

