#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Ability_103162_BP

#include "Basic.hpp"

#include "Hero_1031_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_103162_BP.Ability_103162_BP_C
// 0x0000 (0x3580 - 0x3580)
class UAbility_103162_BP_C final : public UAbility_103162
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_103162_BP_C">();
	}
	static class UAbility_103162_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_103162_BP_C>();
	}
};

}

