#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Ability_105232_BP

#include "Basic.hpp"

#include "PyAbility_105232_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_105232_BP.Ability_105232_BP_C
// 0x0000 (0x2628 - 0x2628)
class UAbility_105232_BP_C final : public UPyAbility_105232
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_105232_BP_C">();
	}
	static class UAbility_105232_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_105232_BP_C>();
	}
};

}

