#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Ability_104971_BP

#include "Basic.hpp"

#include "PyAbility_104971_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_104971_BP.Ability_104971_BP_C
// 0x0000 (0x2768 - 0x2768)
class UAbility_104971_BP_C final : public UPyAbility_104971
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_104971_BP_C">();
	}
	static class UAbility_104971_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_104971_BP_C>();
	}
};

}

