#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Ability_104761_BP

#include "Basic.hpp"

#include "PyAbility_104761_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_104761_BP.Ability_104761_BP_C
// 0x0000 (0x2628 - 0x2628)
class UAbility_104761_BP_C final : public UPyAbility_104761_New
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_104761_BP_C">();
	}
	static class UAbility_104761_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_104761_BP_C>();
	}
};

}

