#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: achievement_utils

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// PythonClass achievement_utils.PyAchievementInsideChecker
// 0x0010 (0x04A0 - 0x0490)
class APyAchievementInsideChecker final : public AActor
{
public:
	int32                                         BelongAchievementID;                               // 0x0490(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_494[0x4];                                      // 0x0494(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ULevelScopeCheckComponent*              CheckComp;                                         // 0x0498(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, EditConst, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyAchievementInsideChecker">();
	}
	static class APyAchievementInsideChecker* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyAchievementInsideChecker>();
	}
};

// PythonClass achievement_utils.PyInsideChecker
// 0x0008 (0x0498 - 0x0490)
class APyInsideChecker final : public AActor
{
public:
	class ULevelScopeCheckComponent*              CheckComp;                                         // 0x0490(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, EditConst, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyInsideChecker">();
	}
	static class APyInsideChecker* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyInsideChecker>();
	}
};

}

