#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ActorSequence

#include "Basic.hpp"

#include "ActorSequence_structs.hpp"
#include "MovieScene_structs.hpp"
#include "MovieScene_classes.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// Class ActorSequence.ActorSequence
// 0x0028 (0x0098 - 0x0070)
class UActorSequence final : public UMovieSceneSequence
{
public:
	class UMovieScene*                            MovieScene;                                        // 0x0070(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, PersistentInstance, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	struct FActorSequenceObjectReferenceMap       ObjectReferences;                                  // 0x0078(0x0020)(NativeAccessSpecifierPrivate)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"ActorSequence">();
	}
	static class UActorSequence* GetDefaultObj()
	{
		return GetDefaultObjImpl<UActorSequence>();
	}
};

// Class ActorSequence.ActorSequenceComponent
// 0x0030 (0x0120 - 0x00F0)
class UActorSequenceComponent : public UActorComponent
{
public:
	struct FMovieSceneSequencePlaybackSettings    PlaybackSettings;                                  // 0x00F0(0x0020)(Edit, NoDestructor, Protected, NativeAccessSpecifierProtected)
	class UActorSequence*                         Sequence;                                          // 0x0110(0x0008)(Edit, ExportObject, ZeroConstructor, InstancedReference, NoDestructor, Protected, PersistentInstance, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UActorSequencePlayer*                   SequencePlayer;                                    // 0x0118(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)

public:
	void PauseSequence();
	void PlaySequence();
	void StopSequence();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"ActorSequenceComponent">();
	}
	static class UActorSequenceComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UActorSequenceComponent>();
	}
};

// Class ActorSequence.ActorSequencePlayer
// 0x0008 (0x04E0 - 0x04D8)
class UActorSequencePlayer final : public UMovieSceneSequencePlayer
{
public:
	uint8                                         Pad_4D8[0x8];                                      // 0x04D8(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"ActorSequencePlayer">();
	}
	static class UActorSequencePlayer* GetDefaultObj()
	{
		return GetDefaultObjImpl<UActorSequencePlayer>();
	}
};

}

