#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AIMoveControl_1047AvoidEnemy

#include "Basic.hpp"

#include "MarvelAI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AIMoveControl_1047AvoidEnemy.AIMoveControl_1047AvoidEnemy_C
// 0x0000 (0x00B8 - 0x00B8)
class UAIMoveControl_1047AvoidEnemy_C final : public UAIAbilityMoveControlLogic
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AIMoveControl_1047AvoidEnemy_C">();
	}
	static class UAIMoveControl_1047AvoidEnemy_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAIMoveControl_1047AvoidEnemy_C>();
	}
};

}

