#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Ammo_104311_BP

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ammo_104311_BP.Ammo_104311_BP_C
// 0x0000 (0x0D80 - 0x0D80)
class AAmmo_104311_BP_C final : public AInstantAmmo
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ammo_104311_BP_C">();
	}
	static class AAmmo_104311_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AAmmo_104311_BP_C>();
	}
};

}

