#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BuffAbility_10415101_BP

#include "Basic.hpp"

#include "Hero_1041_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BuffAbility_10415101_BP.BuffAbility_10415101_BP_C
// 0x0000 (0x1150 - 0x1150)
class UBuffAbility_10415101_BP_C final : public UBuffAbility_10415101
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BuffAbility_10415101_BP_C">();
	}
	static class UBuffAbility_10415101_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBuffAbility_10415101_BP_C>();
	}
};

}

