#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Effect_Damage

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Effect_Damage.Effect_Damage_C
// 0x0000 (0x16C8 - 0x16C8)
class UEffect_Damage_C final : public UMarvelGameplayEffectDamage
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Effect_Damage_C">();
	}
	static class UEffect_Damage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEffect_Damage_C>();
	}
};

}

