#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Effect_2008

#include "Basic.hpp"

#include "MarvelLevel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Effect_2008.Effect_2008_C
// 0x0000 (0x13A0 - 0x13A0)
class UEffect_2008_C final : public ULevelGravityZoneEffectTemplate
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Effect_2008_C">();
	}
	static class UEffect_2008_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEffect_2008_C>();
	}
};

}

