#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Hero_1047

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Hero_1047_structs.hpp"
#include "Marvel_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "GameplayTags_structs.hpp"


namespace SDK::Params
{

// Function Hero_1047.Projectile_10471101.GetProjectileFlyingTime
// 0x0004 (0x0004 - 0x0000)
struct Projectile_10471101_GetProjectileFlyingTime final
{
public:
	float                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.Projectile_10471101.OnJeffProjectileStop
// 0x0170 (0x0170 - 0x0000)
struct Projectile_10471101_OnJeffProjectileStop final
{
public:
	struct FHitResult                             ImpactResult;                                      // 0x0000(0x0170)(ConstParm, Parm, OutParm, ReferenceParm, ContainsInstancedReference, NativeAccessSpecifierPublic)
};

// Function Hero_1047.Cue_Ability_Loop_10471102.ApplyDebugHapplyBubbles
// 0x0004 (0x0004 - 0x0000)
struct Cue_Ability_Loop_10471102_ApplyDebugHapplyBubbles final
{
public:
	int32                                         FrameIndex;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.Cue_Ability_Loop_10471102.ApplyDebugHapplyBubblesSpline
// 0x0010 (0x0010 - 0x0000)
struct Cue_Ability_Loop_10471102_ApplyDebugHapplyBubblesSpline final
{
public:
	int32                                         FrameIndex;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class USplineComponent*                       Spline;                                            // 0x0008(0x0008)(Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.Cue_Ability_Loop_10471102.GetDebugHapplyMinAndMaxFrame
// 0x0008 (0x0008 - 0x0000)
struct Cue_Ability_Loop_10471102_GetDebugHapplyMinAndMaxFrame final
{
public:
	int32                                         Min;                                               // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         Max;                                               // 0x0004(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.Cue_Projectile_HitImpact_10471101.OnPostExecuteAudioCreateShotActor
// 0x0010 (0x0010 - 0x0000)
struct Cue_Projectile_HitImpact_10471101_OnPostExecuteAudioCreateShotActor final
{
public:
	class AOneShotAudioActor*                     OneShotActor;                                      // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class AActor*                                 MyTarget;                                          // 0x0008(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.Projectile_10471301.K2_JeffPaintOnLocation
// 0x0038 (0x0038 - 0x0000)
struct Projectile_10471301_K2_JeffPaintOnLocation final
{
public:
	struct FJeffPaintParams                       Param;                                             // 0x0000(0x0038)(Parm, NoDestructor, NativeAccessSpecifierPublic)
};

// Function Hero_1047.JeffWinterFestivalLibrary.JeffPaintOnLocation
// 0x0038 (0x0038 - 0x0000)
struct JeffWinterFestivalLibrary_JeffPaintOnLocation final
{
public:
	struct FJeffPaintParams                       Param;                                             // 0x0000(0x0038)(Parm, NoDestructor, NativeAccessSpecifierPublic)
};

// Function Hero_1047.Cue_Ability_Loop_10473101.CheckMovementModeByState
// 0x0010 (0x0010 - 0x0000)
struct Cue_Ability_Loop_10473101_CheckMovementModeByState final
{
public:
	class ACharacter*                             Character;                                         // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EMovementMode                                 PrevMovementMode;                                  // 0x0008(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         PreviousCustomMode;                                // 0x0009(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_A[0x6];                                        // 0x000A(0x0006)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// Function Hero_1047.Cue_Ability_Loop_10473101.OnSystemFinished
// 0x0008 (0x0008 - 0x0000)
struct Cue_Ability_Loop_10473101_OnSystemFinished final
{
public:
	class UNiagaraComponent*                      PSystem;                                           // 0x0000(0x0008)(Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.Summoned_10475101.OnActorOverlap
// 0x0008 (0x0008 - 0x0000)
struct Summoned_10475101_OnActorOverlap final
{
public:
	class AActor*                                 InActor;                                           // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.Projectile_10475101.CheckBubblePlacingSpace
// 0x0190 (0x0190 - 0x0000)
struct Projectile_10475101_CheckBubblePlacingSpace final
{
public:
	struct FVector                                BubbleLocation;                                    // 0x0000(0x0018)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FHitResult                             InHitResult;                                       // 0x0018(0x0170)(ConstParm, Parm, OutParm, ReferenceParm, ContainsInstancedReference, NativeAccessSpecifierPublic)
	float                                         BubbleRadius;                                      // 0x0188(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ReturnValue;                                       // 0x018C(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_18D[0x3];                                      // 0x018D(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// Function Hero_1047.Cue_Ability_Loop_10476101.OnJeffStateUpdate
// 0x0001 (0x0001 - 0x0000)
struct Cue_Ability_Loop_10476101_OnJeffStateUpdate final
{
public:
	EJeffState                                    InState;                                           // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.Cue_Ability_Loop_10476101.OnOwnerTagUpdate
// 0x0010 (0x0010 - 0x0000)
struct Cue_Ability_Loop_10476101_OnOwnerTagUpdate final
{
public:
	struct FGameplayTag                           Tag;                                               // 0x0000(0x000C)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          TagExists;                                         // 0x000C(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_D[0x3];                                        // 0x000D(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// Function Hero_1047.Cue_Ability_Loop_Jeff_Diving.OnJeffStateUpdate
// 0x0001 (0x0001 - 0x0000)
struct Cue_Ability_Loop_Jeff_Diving_OnJeffStateUpdate final
{
public:
	EJeffState                                    InState;                                           // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.Ability_104771.ExpandCapsuleSize
// 0x0001 (0x0001 - 0x0000)
struct Ability_104771_ExpandCapsuleSize final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.Ability_104771.GetAliveDevouredCharacter
// 0x0010 (0x0010 - 0x0000)
struct Ability_104771_GetAliveDevouredCharacter final
{
public:
	TArray<class AActor*>                         ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)
};

// Function Hero_1047.Ability_104771.HandleOwnerBuff
// 0x0008 (0x0008 - 0x0000)
struct Ability_104771_HandleOwnerBuff final
{
public:
	int32                                         BuffID;                                            // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bNeedApply;                                        // 0x0004(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// Function Hero_1047.Ability_104771.OnDevouredCharacterDeath
// 0x0028 (0x0028 - 0x0000)
struct Ability_104771_OnDevouredCharacterDeath final
{
public:
	class AActor*                                 InSourceAvatar;                                    // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class AActor*                                 InTargetAvatar;                                    // 0x0008(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FAttributeModifierHandle               ModifierParameterHandle;                           // 0x0010(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.Ability_104771.OnDevouredCharacterDisguiseEnd
// 0x0018 (0x0018 - 0x0000)
struct Ability_104771_OnDevouredCharacterDisguiseEnd final
{
public:
	class AMarvelBaseCharacter*                   InDisguiseCharacter;                               // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class AMarvelBaseCharacter*                   InOriginCharacter;                                 // 0x0008(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIsAvatorAlive;                                    // 0x0010(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// Function Hero_1047.Ability_104771.OnDevourSummonedEndAgentTask
// 0x0008 (0x0008 - 0x0000)
struct Ability_104771_OnDevourSummonedEndAgentTask final
{
public:
	class AActor*                                 InSummoned;                                        // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.Ability_104771.OnSelectRegionFinish
// 0x0001 (0x0001 - 0x0000)
struct Ability_104771_OnSelectRegionFinish final
{
public:
	bool                                          bActivateByTimerOrMT;                              // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.Ability_104771.ReStartDivingBuff
// 0x0004 (0x0004 - 0x0000)
struct Ability_104771_ReStartDivingBuff final
{
public:
	float                                         RemainDuration;                                    // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.Ability_104771.RestoreCapsuleSize
// 0x0001 (0x0001 - 0x0000)
struct Ability_104771_RestoreCapsuleSize final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.Ability_104771.SetCurrentAbilityState
// 0x0001 (0x0001 - 0x0000)
struct Ability_104771_SetCurrentAbilityState final
{
public:
	EAbilityState_104771                          CurrentAbilityState_0;                             // 0x0000(0x0001)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.Ability_104771.SetDevourCharactersFromScope
// 0x0010 (0x0010 - 0x0000)
struct Ability_104771_SetDevourCharactersFromScope final
{
public:
	TArray<TWeakObjectPtr<class AActor>>          InDevourCharactersList;                            // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, UObjectWrapper, NativeAccessSpecifierPublic)
};

// Function Hero_1047.Ability_104771.SpitOutImpl
// 0x0003 (0x0003 - 0x0000)
struct Ability_104771_SpitOutImpl final
{
public:
	bool                                          bSpitOutAll;                                       // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bSpitOutEnemy;                                     // 0x0001(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bKnockUp;                                          // 0x0002(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.Ability_104771.StopDivingBuff
// 0x0004 (0x0004 - 0x0000)
struct Ability_104771_StopDivingBuff final
{
public:
	float                                         ReturnValue;                                       // 0x0000(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.Ability_104771.SwitchSelectionRegionTopView
// 0x0002 (0x0002 - 0x0000)
struct Ability_104771_SwitchSelectionRegionTopView final
{
public:
	bool                                          bToTopView;                                        // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bButtonSwitch;                                     // 0x0001(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.Ability_104771.GetCurrentAbilityState
// 0x0001 (0x0001 - 0x0000)
struct Ability_104771_GetCurrentAbilityState final
{
public:
	EAbilityState_104771                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.Ability_104771.GetDevouredAlly
// 0x0010 (0x0010 - 0x0000)
struct Ability_104771_GetDevouredAlly final
{
public:
	TArray<class AActor*>                         ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)
};

// Function Hero_1047.Ability_104771.GetDevouredEnemy
// 0x0010 (0x0010 - 0x0000)
struct Ability_104771_GetDevouredEnemy final
{
public:
	TArray<class AActor*>                         ReturnValue;                                       // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, NativeAccessSpecifierPublic)
};

// Function Hero_1047.Ability_104771.HaveDevouredAlly
// 0x0001 (0x0001 - 0x0000)
struct Ability_104771_HaveDevouredAlly final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.Ability_104771.HaveDevouredEnemy
// 0x0001 (0x0001 - 0x0000)
struct Ability_104771_HaveDevouredEnemy final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.JeffPassengerContainerComponent.Client_AttachPassengerAndUpdateComponentTickPrerequisite
// 0x0008 (0x0008 - 0x0000)
struct JeffPassengerContainerComponent_Client_AttachPassengerAndUpdateComponentTickPrerequisite final
{
public:
	class AActor*                                 InAttachPassenger;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.JeffPassengerContainerComponent.Client_DetachPassengerAndUpdateComponentTickPrerequisite
// 0x0008 (0x0008 - 0x0000)
struct JeffPassengerContainerComponent_Client_DetachPassengerAndUpdateComponentTickPrerequisite final
{
public:
	class AActor*                                 InDetachPassenger;                                 // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.EffectiveComponent_10477101.K2_OnPreApplyContainer
// 0x0020 (0x0020 - 0x0000)
struct EffectiveComponent_10477101_K2_OnPreApplyContainer final
{
public:
	TArray<struct FHitResult>                     HitResults;                                        // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, ContainsInstancedReference, NativeAccessSpecifierPublic)
	TArray<struct FHitResult>                     ReturnValue;                                       // 0x0010(0x0010)(Parm, OutParm, ZeroConstructor, ReturnParm, ContainsInstancedReference, NativeAccessSpecifierPublic)
};

// Function Hero_1047.MarvelAbilityTask_SelectRegionAttack.SelectRegionAttack
// 0x0020 (0x0020 - 0x0000)
struct MarvelAbilityTask_SelectRegionAttack_SelectRegionAttack final
{
public:
	class UMarvelGameplayAbility*                 OwningAbility;                                     // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   ConfirmMethodName;                                 // 0x0008(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         SelectionWarningDuration;                          // 0x0014(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UMarvelAbilityTask_SelectRegionAttack*  ReturnValue;                                       // 0x0018(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.MarvelAbilityTask_SelectRegionAttack.OnLocateFinish
// 0x0001 (0x0001 - 0x0000)
struct MarvelAbilityTask_SelectRegionAttack_OnLocateFinish final
{
public:
	bool                                          bActiveByTimerOrMT;                                // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.MarvelAbilityTask_SelectRegionAttack.OnPressActivateHurricaneKey
// 0x0004 (0x0004 - 0x0000)
struct MarvelAbilityTask_SelectRegionAttack_OnPressActivateHurricaneKey final
{
public:
	float                                         TimeWaited;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.MarvelAbilityTask_SelectRegionAttack.OnPressCameraAnimationKey
// 0x0004 (0x0004 - 0x0000)
struct MarvelAbilityTask_SelectRegionAttack_OnPressCameraAnimationKey final
{
public:
	float                                         TimeWaited;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.MarvelAbilityTask_SelectRegionAttack.OnReleaseCameraAnimationKey
// 0x0004 (0x0004 - 0x0000)
struct MarvelAbilityTask_SelectRegionAttack_OnReleaseCameraAnimationKey final
{
public:
	float                                         TimeWaited;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.Cue_Ability_Loop_10477101.OnSelectRegionFinish
// 0x0001 (0x0001 - 0x0000)
struct Cue_Ability_Loop_10477101_OnSelectRegionFinish final
{
public:
	bool                                          bActivateByTimerOrMT;                              // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.Ability_104781.BindDettachDelegates
// 0x0008 (0x0008 - 0x0000)
struct Ability_104781_BindDettachDelegates final
{
public:
	class AActor*                                 InGroot;                                           // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.Ability_104781.MarkOnGroot
// 0x0001 (0x0001 - 0x0000)
struct Ability_104781_MarkOnGroot final
{
public:
	bool                                          bOnGroot;                                          // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.Ability_104781.OnCoopAbilityTickStateChanged
// 0x0001 (0x0001 - 0x0000)
struct Ability_104781_OnCoopAbilityTickStateChanged final
{
public:
	bool                                          bShouldAbilityTick;                                // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.Ability_104781.OnGrootDeath
// 0x0028 (0x0028 - 0x0000)
struct Ability_104781_OnGrootDeath final
{
public:
	class AActor*                                 InSourceAvatar;                                    // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class AActor*                                 InTargetAvatar;                                    // 0x0008(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FAttributeModifierHandle               ModifierParameterHandle;                           // 0x0010(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.Ability_104781.OnGrootTagUpdated
// 0x0010 (0x0010 - 0x0000)
struct Ability_104781_OnGrootTagUpdated final
{
public:
	struct FGameplayTag                           TagUpdated;                                        // 0x0000(0x000C)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bTagExists;                                        // 0x000C(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_D[0x3];                                        // 0x000D(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// Function Hero_1047.Ability_104781.OnJeffDeath
// 0x0028 (0x0028 - 0x0000)
struct Ability_104781_OnJeffDeath final
{
public:
	class AActor*                                 InSourceAvatar;                                    // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class AActor*                                 InTargetAvatar;                                    // 0x0008(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FAttributeModifierHandle               ModifierParameterHandle;                           // 0x0010(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.Ability_104781.OnJeffTagUpdated
// 0x0010 (0x0010 - 0x0000)
struct Ability_104781_OnJeffTagUpdated final
{
public:
	struct FGameplayTag                           TagUpdated;                                        // 0x0000(0x000C)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bTagExists;                                        // 0x000C(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_D[0x3];                                        // 0x000D(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// Function Hero_1047.Ability_104781.OnJeffTakeDamage
// 0x0028 (0x0028 - 0x0000)
struct Ability_104781_OnJeffTakeDamage final
{
public:
	class AActor*                                 InSourceAvatar;                                    // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class AActor*                                 InTargetAvatar;                                    // 0x0008(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FAttributeModifierHandle               ModifierParameterHandle;                           // 0x0010(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.Ability_104781.OnRideCancel
// 0x0004 (0x0004 - 0x0000)
struct Ability_104781_OnRideCancel final
{
public:
	float                                         StateIntervalTime;                                 // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.Ability_104781.ScaleRidingHitShapeSize
// 0x0001 (0x0001 - 0x0000)
struct Ability_104781_ScaleRidingHitShapeSize final
{
public:
	bool                                          bEnable;                                           // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.Ability_104781.ServerOnRideCancel
// 0x0004 (0x0004 - 0x0000)
struct Ability_104781_ServerOnRideCancel final
{
public:
	float                                         StateIntervalTime;                                 // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.Ability_104781.SetJeffState
// 0x0001 (0x0001 - 0x0000)
struct Ability_104781_SetJeffState final
{
public:
	EJeffGrootAbilityState                        InState;                                           // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.Ability_104781.SetSpringArmIgnore
// 0x0018 (0x0018 - 0x0000)
struct Ability_104781_SetSpringArmIgnore final
{
public:
	class AMarvelBaseCharacter*                   InGroot;                                           // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class AMarvelBaseCharacter*                   OwnChar;                                           // 0x0008(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIgnore;                                           // 0x0010(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// Function Hero_1047.Ability_104781.UnBindDettachDelegates
// 0x0008 (0x0008 - 0x0000)
struct Ability_104781_UnBindDettachDelegates final
{
public:
	class AActor*                                 InGroot;                                           // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.Cue_Ability_Loop_10478101.OnJeffGrootCoopStateChange
// 0x0001 (0x0001 - 0x0000)
struct Cue_Ability_Loop_10478101_OnJeffGrootCoopStateChange final
{
public:
	EJeffGrootAbilityState                        InState;                                           // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.JeffAnimInstance.CalucateJeffGrootIK
// 0x0010 (0x0010 - 0x0000)
struct JeffAnimInstance_CalucateJeffGrootIK final
{
public:
	struct FAnimComponentSpacePoseContext         PoseContext;                                       // 0x0000(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
};

// Function Hero_1047.JeffAnimInstance.GetGroundMotionForwardState
// 0x0010 (0x0010 - 0x0000)
struct JeffAnimInstance_GetGroundMotionForwardState final
{
public:
	struct FAnimPoseContext                       PoseContext;                                       // 0x0000(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
};

// Function Hero_1047.JeffAnimInstance.RelevantJeffOnGrootStateNode
// 0x0020 (0x0020 - 0x0000)
struct JeffAnimInstance_RelevantJeffOnGrootStateNode final
{
public:
	struct FAnimUpdateContext                     Context;                                           // 0x0000(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FAnimNodeReference                     Node;                                              // 0x0010(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
};

// Function Hero_1047.JeffAnimInstance.UpdateJeffOnGrootMotionNode
// 0x0020 (0x0020 - 0x0000)
struct JeffAnimInstance_UpdateJeffOnGrootMotionNode final
{
public:
	struct FAnimUpdateContext                     Context;                                           // 0x0000(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FAnimNodeReference                     Node;                                              // 0x0010(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
};

// Function Hero_1047.JeffAnimInstance.UpdateJeffOnGrootStateNode
// 0x0020 (0x0020 - 0x0000)
struct JeffAnimInstance_UpdateJeffOnGrootStateNode final
{
public:
	struct FAnimUpdateContext                     Context;                                           // 0x0000(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FAnimNodeReference                     Node;                                              // 0x0010(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
};

// Function Hero_1047.JeffCharacter.DivingBlockAbility
// 0x0070 (0x0070 - 0x0000)
struct JeffCharacter_DivingBlockAbility final
{
public:
	struct FGameplayTagContainer                  InContainer;                                       // 0x0000(0x0068)(Parm, NativeAccessSpecifierPublic)
	bool                                          bBlock;                                            // 0x0068(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_69[0x7];                                       // 0x0069(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// Function Hero_1047.JeffCharacter.GetJeffState
// 0x0001 (0x0001 - 0x0000)
struct JeffCharacter_GetJeffState final
{
public:
	EJeffState                                    ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.JeffCharacter.IsJeffDiving
// 0x0001 (0x0001 - 0x0000)
struct JeffCharacter_IsJeffDiving final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.JeffCharacter.IsJeffMovingForward
// 0x0001 (0x0001 - 0x0000)
struct JeffCharacter_IsJeffMovingForward final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.JeffCharacter.SafeMove
// 0x0018 (0x0018 - 0x0000)
struct JeffCharacter_SafeMove final
{
public:
	struct FVector                                Delta;                                             // 0x0000(0x0018)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.JeffCharacter.SetJeffState
// 0x0001 (0x0001 - 0x0000)
struct JeffCharacter_SetJeffState final
{
public:
	EJeffState                                    InState;                                           // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.JeffChildActor.OnCharacterDeath
// 0x0028 (0x0028 - 0x0000)
struct JeffChildActor_OnCharacterDeath final
{
public:
	class AActor*                                 OutSourceAvatar;                                   // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class AActor*                                 OutTargetAvatar;                                   // 0x0008(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FAttributeModifierHandle               ModifierParameterHandle;                           // 0x0010(0x0018)(ConstParm, Parm, OutParm, ReferenceParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.JeffChildActor.OnCharacterReborn
// 0x0740 (0x0740 - 0x0000)
struct JeffChildActor_OnCharacterReborn final
{
public:
	class AActor*                                 OutTargetActor;                                    // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_8[0x8];                                        // 0x0008(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FCharacterRebornParam                  Param;                                             // 0x0010(0x0730)(ConstParm, Parm, OutParm, ReferenceParm, ContainsInstancedReference, NativeAccessSpecifierPublic)
};

// Function Hero_1047.JeffChildActor.OnCharacterSwimEnd
// 0x000C (0x000C - 0x0000)
struct JeffChildActor_OnCharacterSwimEnd final
{
public:
	class FName                                   Tag;                                               // 0x0000(0x000C)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.JeffChildActor.OnJeffStateChange
// 0x0001 (0x0001 - 0x0000)
struct JeffChildActor_OnJeffStateChange final
{
public:
	EJeffState                                    InState;                                           // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.JeffChildActor.OnTagUpdate
// 0x0010 (0x0010 - 0x0000)
struct JeffChildActor_OnTagUpdate final
{
public:
	struct FGameplayTag                           Tag;                                               // 0x0000(0x000C)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bTagExists;                                        // 0x000C(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_D[0x3];                                        // 0x000D(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// Function Hero_1047.JeffChildActor.SetDivingMarteialSectionHidden
// 0x0001 (0x0001 - 0x0000)
struct JeffChildActor_SetDivingMarteialSectionHidden final
{
public:
	bool                                          bDiving;                                           // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.Cue_Ability_Loop_10470101.OnTagUpdate
// 0x0010 (0x0010 - 0x0000)
struct Cue_Ability_Loop_10470101_OnTagUpdate final
{
public:
	struct FGameplayTag                           TagUpdated;                                        // 0x0000(0x000C)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bTagExists;                                        // 0x000C(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_D[0x3];                                        // 0x000D(0x0003)(Fixing Struct Size After Last Property [ Dumper-7 ])
};

// Function Hero_1047.FlowSimluateSplineActor.BuildCurrentSplinePoints
// 0x0004 (0x0004 - 0x0000)
struct FlowSimluateSplineActor_BuildCurrentSplinePoints final
{
public:
	float                                         DeltaTime;                                         // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

// Function Hero_1047.JeffGroundMotionSubAnimInstance.EnterBToF
// 0x0020 (0x0020 - 0x0000)
struct JeffGroundMotionSubAnimInstance_EnterBToF final
{
public:
	struct FAnimUpdateContext                     Context;                                           // 0x0000(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FAnimNodeReference                     Node;                                              // 0x0010(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
};

// Function Hero_1047.JeffGroundMotionSubAnimInstance.RelevantBlackforwadTransitionNode
// 0x0020 (0x0020 - 0x0000)
struct JeffGroundMotionSubAnimInstance_RelevantBlackforwadTransitionNode final
{
public:
	struct FAnimUpdateContext                     Context;                                           // 0x0000(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FAnimNodeReference                     Node;                                              // 0x0010(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
};

// Function Hero_1047.JeffGroundMotionSubAnimInstance.RelevantCycleNode
// 0x0020 (0x0020 - 0x0000)
struct JeffGroundMotionSubAnimInstance_RelevantCycleNode final
{
public:
	struct FAnimUpdateContext                     Context;                                           // 0x0000(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FAnimNodeReference                     Node;                                              // 0x0010(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
};

// Function Hero_1047.JeffGroundMotionSubAnimInstance.RelevantJumpStartNode
// 0x0020 (0x0020 - 0x0000)
struct JeffGroundMotionSubAnimInstance_RelevantJumpStartNode final
{
public:
	struct FAnimUpdateContext                     Context;                                           // 0x0000(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FAnimNodeReference                     Node;                                              // 0x0010(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
};

// Function Hero_1047.JeffGroundMotionSubAnimInstance.RelevantLeftForwardNode
// 0x0020 (0x0020 - 0x0000)
struct JeffGroundMotionSubAnimInstance_RelevantLeftForwardNode final
{
public:
	struct FAnimUpdateContext                     Context;                                           // 0x0000(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FAnimNodeReference                     Node;                                              // 0x0010(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
};

// Function Hero_1047.JeffGroundMotionSubAnimInstance.RelevantRightForwardNode
// 0x0020 (0x0020 - 0x0000)
struct JeffGroundMotionSubAnimInstance_RelevantRightForwardNode final
{
public:
	struct FAnimUpdateContext                     Context;                                           // 0x0000(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FAnimNodeReference                     Node;                                              // 0x0010(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
};

// Function Hero_1047.JeffGroundMotionSubAnimInstance.RelevantStopNode
// 0x0020 (0x0020 - 0x0000)
struct JeffGroundMotionSubAnimInstance_RelevantStopNode final
{
public:
	struct FAnimUpdateContext                     Context;                                           // 0x0000(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FAnimNodeReference                     Node;                                              // 0x0010(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
};

// Function Hero_1047.JeffGroundMotionSubAnimInstance.UpdateAllBackforwardNode
// 0x0020 (0x0020 - 0x0000)
struct JeffGroundMotionSubAnimInstance_UpdateAllBackforwardNode final
{
public:
	struct FAnimUpdateContext                     Context;                                           // 0x0000(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FAnimNodeReference                     Node;                                              // 0x0010(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
};

// Function Hero_1047.JeffGroundMotionSubAnimInstance.UpdateBlackforwadTransitionNode
// 0x0020 (0x0020 - 0x0000)
struct JeffGroundMotionSubAnimInstance_UpdateBlackforwadTransitionNode final
{
public:
	struct FAnimUpdateContext                     Context;                                           // 0x0000(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FAnimNodeReference                     Node;                                              // 0x0010(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
};

// Function Hero_1047.JeffGroundMotionSubAnimInstance.UpdateForwardNode
// 0x0020 (0x0020 - 0x0000)
struct JeffGroundMotionSubAnimInstance_UpdateForwardNode final
{
public:
	struct FAnimUpdateContext                     Context;                                           // 0x0000(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FAnimNodeReference                     Node;                                              // 0x0010(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
};

// Function Hero_1047.JeffGroundMotionSubAnimInstance.UpdateJumpLandNode
// 0x0020 (0x0020 - 0x0000)
struct JeffGroundMotionSubAnimInstance_UpdateJumpLandNode final
{
public:
	struct FAnimUpdateContext                     Context;                                           // 0x0000(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FAnimNodeReference                     Node;                                              // 0x0010(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
};

// Function Hero_1047.JeffGroundMotionSubAnimInstance.UpdateJumpLoopNode
// 0x0020 (0x0020 - 0x0000)
struct JeffGroundMotionSubAnimInstance_UpdateJumpLoopNode final
{
public:
	struct FAnimUpdateContext                     Context;                                           // 0x0000(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FAnimNodeReference                     Node;                                              // 0x0010(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
};

// Function Hero_1047.JeffGroundMotionSubAnimInstance.UpdateJumpStartNode
// 0x0020 (0x0020 - 0x0000)
struct JeffGroundMotionSubAnimInstance_UpdateJumpStartNode final
{
public:
	struct FAnimUpdateContext                     Context;                                           // 0x0000(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FAnimNodeReference                     Node;                                              // 0x0010(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
};

// Function Hero_1047.JeffGroundMotionSubAnimInstance.UpdateLeftForwardNode
// 0x0020 (0x0020 - 0x0000)
struct JeffGroundMotionSubAnimInstance_UpdateLeftForwardNode final
{
public:
	struct FAnimUpdateContext                     Context;                                           // 0x0000(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FAnimNodeReference                     Node;                                              // 0x0010(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
};

// Function Hero_1047.JeffGroundMotionSubAnimInstance.UpdateRightForwardNode
// 0x0020 (0x0020 - 0x0000)
struct JeffGroundMotionSubAnimInstance_UpdateRightForwardNode final
{
public:
	struct FAnimUpdateContext                     Context;                                           // 0x0000(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NativeAccessSpecifierPublic)
	struct FAnimNodeReference                     Node;                                              // 0x0010(0x0010)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
};

// Function Hero_1047.JeffMovementComponent.CheckMoveForward
// 0x0090 (0x0090 - 0x0000)
struct JeffMovementComponent_CheckMoveForward final
{
public:
	struct FVector                                MoveDelta;                                         // 0x0000(0x0018)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_18[0x8];                                       // 0x0018(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FJeffMoveForwardCheckResult            ReturnValue;                                       // 0x0020(0x0070)(Parm, OutParm, ReturnParm, NoDestructor, NativeAccessSpecifierPublic)
};

// Function Hero_1047.JeffMovementComponent.OnJeffGetOffWall
// 0x0020 (0x0020 - 0x0000)
struct JeffMovementComponent_OnJeffGetOffWall final
{
public:
	struct FWallRunningEndInfo                    InWallRunningEndInfo;                              // 0x0000(0x0020)(ConstParm, Parm, OutParm, ReferenceParm, NoDestructor, NativeAccessSpecifierPublic)
};

}

