#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Hero_1018

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Marvel_structs.hpp"
#include "Marvel_classes.hpp"
#include "Hero_1018_structs.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "GameplayTags_structs.hpp"
#include "GameplayAbilities_structs.hpp"


namespace SDK
{

// Class Hero_1018.Projectile_101811
// 0x0050 (0x30A0 - 0x3050)
class AProjectile_101811 : public AMarvelAbilityTargetActor_Projectile
{
public:
	bool                                          bIsCauserChanged;                                  // 0x3050(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_3051[0x4F];                                    // 0x3051(0x004F)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	const struct FVector GetAimDirection();
	const struct FVector GetAimStart();
	void ResetDefaut();
	void ResetTimeElapsed();
	void SetAimLine(const struct FVector& InAimStart, const struct FVector& InAimDirection);
	void SetProjectileSpreadRotateInfo(const struct FProjectileSpreadRotateInfo& InProjectileSpreadRotateInfo);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"Projectile_101811">();
	}
	static class AProjectile_101811* GetDefaultObj()
	{
		return GetDefaultObjImpl<AProjectile_101811>();
	}
};

// Class Hero_1018.Cue_Ability_Loop_10181901
// 0x00B0 (0x0F00 - 0x0E50)
class ACue_Ability_Loop_10181901 final : public AMarvelCueNotify_Ability
{
public:
	TMap<class USkeletalMeshComponent*, struct FCustomMeshMaterialMap> HandShadowMeshMaterialMap;                         // 0x0E50(0x0050)(BlueprintVisible, ContainsInstancedReference, Protected, NativeAccessSpecifierProtected)
	TMap<uint8, struct FCustomMaterialCurveMap>   MaterialParamMap;                                  // 0x0EA0(0x0050)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, Protected, NativeAccessSpecifierProtected)
	TArray<float>                                 MaterialMultiFactorList;                           // 0x0EF0(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, Protected, NativeAccessSpecifierProtected)

public:
	void CreateCustomMaterial(class USkeletalMeshComponent* InHandShadowComponent);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"Cue_Ability_Loop_10181901">();
	}
	static class ACue_Ability_Loop_10181901* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACue_Ability_Loop_10181901>();
	}
};

// Class Hero_1018.Cue_Ability_Loop_10182101
// 0x0020 (0x0E70 - 0x0E50)
class ACue_Ability_Loop_10182101 final : public AMarvelCueNotify_Ability
{
public:
	class USkeletalMeshComponent*                 SkeletalMesh;                                      // 0x0E50(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class USkeletalMeshComponent*                 SkeletalMesh1;                                     // 0x0E58(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         AddLength;                                         // 0x0E60(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_E64[0x4];                                      // 0x0E64(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UFXSystemAsset*                         HitFXSystemAsset;                                  // 0x0E68(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"Cue_Ability_Loop_10182101">();
	}
	static class ACue_Ability_Loop_10182101* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACue_Ability_Loop_10182101>();
	}
};

// Class Hero_1018.Config_101841
// 0x1F98 (0x2030 - 0x0098)
class UConfig_101841 : public UMarvelAbilityConfig
{
public:
	struct FVector                                BarrierOffset;                                     // 0x0098(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         RestoreSpeed;                                      // 0x00B0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         LimitSpeed;                                        // 0x00B4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MinAngle;                                          // 0x00B8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MaxAngle;                                          // 0x00BC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         InSkyMinAngle;                                     // 0x00C0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         InSkyMaxAngle;                                     // 0x00C4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         BarrierGroundTraceLength;                          // 0x00C8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         BarrierRadius;                                     // 0x00CC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         BarrierHeight;                                     // 0x00D0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         NeedAdjustCollisionAngle;                          // 0x00D4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ForwardOffset;                                     // 0x00D8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         BarrierRecoveryDelay;                              // 0x00DC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         BarrierReactiveDelay;                              // 0x00E0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         UpdateCollisionTime;                               // 0x00E4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         FreeCamBuffID;                                     // 0x00E8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         BarrierMoveCollisionRadius;                        // 0x00EC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FMarvelAbilityTraceContext             MoveCollisionTraceContext;                         // 0x00F0(0x0F90)(Edit, BlueprintVisible, ContainsInstancedReference, NativeAccessSpecifierPublic)
	struct FVector                                MoveCollisionOffset;                               // 0x1080(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1098[0x8];                                     // 0x1098(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FMarvelAbilityTraceContext             TraceContext;                                      // 0x10A0(0x0F90)(Edit, BlueprintVisible, ContainsInstancedReference, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"Config_101841">();
	}
	static class UConfig_101841* GetDefaultObj()
	{
		return GetDefaultObjImpl<UConfig_101841>();
	}
};

// Class Hero_1018.Summoned_10184101
// 0x00A0 (0x09B0 - 0x0910)
class ASummoned_10184101 : public AMarvelBarrierBase
{
public:
	class UConfig_101841*                         AbilityConfig;                                     // 0x0910(0x0008)(BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class AMarvelBaseCharacter*                   SummonerInstigator;                                // 0x0918(0x0008)(BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UMarvelGameplayAbility*                 OwningSummonerAbility;                             // 0x0920(0x0008)(BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         BarrierTraceDistance;                              // 0x0928(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_92C[0x4];                                      // 0x092C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRotator                               CameraRotator;                                     // 0x0930(0x0018)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	struct FRotator                               CurrentRotator;                                    // 0x0948(0x0018)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	struct FVector                                InitLocation;                                      // 0x0960(0x0018)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                LocalInitLocation;                                 // 0x0978(0x0018)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         OffsetAngle;                                       // 0x0990(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Length;                                            // 0x0994(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                CollisionInitRelativeLocation;                     // 0x0998(0x0018)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	bool BarrierTraceGround();
	class AMarvelBaseCharacter* GetOwnerCharacter();
	class UMarvelBaseGameplayAbility* GetOwningAbility();
	class UMarvelAbilityConfig* GetOwningAbilityConfig();
	bool HasFreeCamBuff();
	void K2_OnBeginAgentTask();
	void K2_SetAlive(bool bInAlive);
	void SetBarrierTrans();
	void SetInstigatorAOYaw();
	void SetPitchLimit(float DeltaTime);
	void UpdateBarrierCollisionOffset();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"Summoned_10184101">();
	}
	static class ASummoned_10184101* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASummoned_10184101>();
	}
};

// Class Hero_1018.SummonedComp_10184101
// 0x0010 (0x0CB0 - 0x0CA0)
class USummonedComp_10184101 : public UMarvelSummonedComponent
{
public:
	int32                                         OwningAbilityID;                                   // 0x0CA0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, AdvancedDisplay, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_CA4[0x4];                                      // 0x0CA4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class ASummoned_10184101*                     OwnerBarrierSummoned;                              // 0x0CA8(0x0008)(BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"SummonedComp_10184101">();
	}
	static class USummonedComp_10184101* GetDefaultObj()
	{
		return GetDefaultObjImpl<USummonedComp_10184101>();
	}
};

// Class Hero_1018.Config_101851
// 0x0008 (0x00A0 - 0x0098)
class UConfig_101851 : public UMarvelAbilityConfig
{
public:
	float                                         DarkHealthRate;                                    // 0x0098(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         DarkDamageRate;                                    // 0x009C(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"Config_101851">();
	}
	static class UConfig_101851* GetDefaultObj()
	{
		return GetDefaultObjImpl<UConfig_101851>();
	}
};

// Class Hero_1018.Ability_101851
// 0x0008 (0x2590 - 0x2588)
class UAbility_101851 : public UAbility_108
{
public:
	uint8                                         Pad_2588[0x8];                                     // 0x2588(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	float GetCurrentDarkManaValue();
	float GetDarkManaValue();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"Ability_101851">();
	}
	static class UAbility_101851* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_101851>();
	}
};

// Class Hero_1018.Scope_10185101
// 0x0010 (0x1710 - 0x1700)
class AScope_10185101 final : public AMarvelAbilityTargetActor_Scope
{
public:
	uint8                                         Pad_1700[0x10];                                    // 0x1700(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"Scope_10185101">();
	}
	static class AScope_10185101* GetDefaultObj()
	{
		return GetDefaultObjImpl<AScope_10185101>();
	}
};

// Class Hero_1018.Config_101861
// 0x00B8 (0x0150 - 0x0098)
class UConfig_101861 final : public UMarvelAbilityConfig
{
public:
	struct FVector                                LandscapeCameraTranslation;                        // 0x0098(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                FirstDefaultPlacedTranslation;                     // 0x00B0(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         CharacterToLandscapeInterp;                        // 0x00C8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         LandscapeToCharacterInterp;                        // 0x00CC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<float>                                 CameraMovingMaxSpeeds;                             // 0x00D0(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)
	int32                                         DefaultSpeedLevel;                                 // 0x00E0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         LandscapeCullDistanceSquared;                      // 0x00E4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         TracePortalRadius;                                 // 0x00E8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         PortalSummonerId;                                  // 0x00EC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bSolvePenetration;                                 // 0x00F0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_F1[0x3];                                       // 0x00F1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CollisionShrinkFactor;                             // 0x00F4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         CollisionBoostFactor;                              // 0x00F8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_FC[0x4];                                       // 0x00FC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<ECollisionChannel>                     BlockChannels;                                     // 0x0100(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NativeAccessSpecifierPublic)
	ECollisionChannel                             TraceChannel;                                      // 0x0110(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_111[0x7];                                      // 0x0111(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TSubclassOf<class ATracePortalCameraActor_101861> CameraActorClass;                                  // 0x0118(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSubclassOf<class AActor>                     PrePlaceActorClass;                                // 0x0120(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bCheckLevelPenetration;                            // 0x0128(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_129[0x3];                                      // 0x0129(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   RequiredPenetrationCompTag;                        // 0x012C(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                BoxExtend;                                         // 0x0138(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"Config_101861">();
	}
	static class UConfig_101861* GetDefaultObj()
	{
		return GetDefaultObjImpl<UConfig_101861>();
	}
};

// Class Hero_1018.Ability_101861
// 0x0190 (0x2710 - 0x2580)
class UAbility_101861 : public UMarvelGameplayAbility
{
public:
	class UConfig_101861*                         Config;                                            // 0x2580(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class ATracePortalCameraActor_101861*         CameraActor;                                       // 0x2588(0x0008)(BlueprintVisible, BlueprintReadOnly, Net, ZeroConstructor, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class APlacedPortalActor_101861*              PrePlaceActor;                                     // 0x2590(0x0008)(BlueprintVisible, BlueprintReadOnly, Net, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         KeyReleaseEndAbilityAudioID;                       // 0x2598(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_259C[0x4];                                     // 0x259C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(EPlaceEvent_101861 NewPlaceEvent)> OnExpectPlaceEventChange;                          // 0x25A0(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	class APortalViewActor*                       StartPortal;                                       // 0x25B0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class APortalViewActor*                       EndPortal;                                         // 0x25B8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_25C0[0x10];                                    // 0x25C0(0x0010)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAbilityPlaceMsg_101861                PlaceMsg;                                          // 0x25D0(0x0130)(NoDestructor, Protected, NativeAccessSpecifierProtected)
	uint8                                         Pad_2700[0x10];                                    // 0x2700(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void EmptyEventOnPressOrReleaseInput(float TimeWaited);
	void OnPressCameraDrop(float TimeWaited);
	void OnPressCameraRise(float TimeWaited);
	void OnPressCameraSpeedDown(float TimeWaited);
	void OnPressCameraSpeedUp(float TimeWaited);
	void OnPressEndAbility(float TimeWaited);
	void OnReleaseCameraDrop(float TimeWaited);
	void OnReleaseCameraRise(float TimeWaited);
	void OnReleaseEndAbility(float TimeWaited);
	void OnReleasePlaceOrRemovePortal(float TimeWaited);
	void OnRep_ReplicateCameraActor();
	void OnServerSpawnPortalSuccess(class AActor* SpawnActor);
	void OnViewingCharacterChanged(class AMarvelBaseCharacter* ViewingTarget);
	void ServerHandleEventAndMsg(EPlaceEvent_101861 NewPlaceEvent, const struct FAbilityPlaceMsg_101861& NewPlaceMsg);
	void SimulatedHandleEventAndMsg(EPlaceEvent_101861 NewPlaceEvent, const struct FAbilityPlaceMsg_101861& NewPlaceMsg);

	EPlaceEvent_101861 GetPlaceEvent() const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"Ability_101861">();
	}
	static class UAbility_101861* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_101861>();
	}
};

// Class Hero_1018.TracePortalCameraActor_101861
// 0x0360 (0x1200 - 0x0EA0)
class ATracePortalCameraActor_101861 : public AMovingCameraActor
{
public:
	uint8                                         Pad_E98[0x78];                                     // 0x0E98(0x0078)(Fixing Size After Last Property [ Dumper-7 ])
	bool                                          bIsActive;                                         // 0x0F10(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, Net, ZeroConstructor, EditConst, IsPlainOldData, RepNotify, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_F11[0x7];                                      // 0x0F11(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRepSummonedMovement                   CustomRepMovement;                                 // 0x0F18(0x0200)(Net, RepNotify, ContainsInstancedReference, Protected, NativeAccessSpecifierProtected)
	uint8                                         Pad_1118[0x1];                                     // 0x1118(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	bool                                          bTracingPlacedPortal;                              // 0x1119(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_111A[0x6];                                     // 0x111A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UAbility_101861*                        OwningAbility;                                     // 0x1120(0x0008)(Net, ZeroConstructor, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UConfig_101861*                         AbilityConfig;                                     // 0x1128(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(bool bIsActive, bool bTracingPlacedPortal)> OnStateChange;                                     // 0x1130(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	class UStaticMeshComponent*                   MeshComp;                                          // 0x1140(0x0008)(Edit, BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class USpringArmComponent*                    SpringArmComponent;                                // 0x1148(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, EditConst, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TWeakObjectPtr<class AActor>                  LastHitActor;                                      // 0x1150(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSet<class AActor*>                           IntersectedTransparentActors;                      // 0x1158(0x0050)(NativeAccessSpecifierPublic)
	uint8                                         Pad_11A8[0x58];                                    // 0x11A8(0x0058)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void NetMulticastInitTransform(const struct FTransform& InitTransform);
	void OnBirthBaseActiveDispatch(class AActor* InBirthBase);
	void OnRep_bIsActive();
	void OnRep_CustomRepMovement();
	void OnRep_OwningAbility();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"TracePortalCameraActor_101861">();
	}
	static class ATracePortalCameraActor_101861* GetDefaultObj()
	{
		return GetDefaultObjImpl<ATracePortalCameraActor_101861>();
	}
};

// Class Hero_1018.PlacedPortalActor_101861
// 0x02C0 (0x0750 - 0x0490)
class APlacedPortalActor_101861 : public AActor
{
public:
	uint8                                         Pad_490[0x80];                                     // 0x0490(0x0080)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTag                           CueTag;                                            // 0x0510(0x000C)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_51C[0x4];                                      // 0x051C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(bool bIsActive, bool bTracingPlacedPortal)> OnStateChange;                                     // 0x0520(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	class USphereComponent*                       RootSphereComp;                                    // 0x0530(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UConfig_101861*                         AbilityConfig;                                     // 0x0538(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIsActive;                                         // 0x0540(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, Net, ZeroConstructor, EditConst, IsPlainOldData, RepNotify, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_541[0x7];                                      // 0x0541(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRepSummonedMovement                   CustomRepMovement;                                 // 0x0548(0x0200)(Net, RepNotify, ContainsInstancedReference, Protected, NativeAccessSpecifierProtected)
	uint8                                         Pad_748[0x8];                                      // 0x0748(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void OnRep_bIsActive();
	void OnRep_CustomRepMovement();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PlacedPortalActor_101861">();
	}
	static class APlacedPortalActor_101861* GetDefaultObj()
	{
		return GetDefaultObjImpl<APlacedPortalActor_101861>();
	}
};

// Class Hero_1018.Cue_Ability_Loop_10186101
// 0x0008 (0x0E58 - 0x0E50)
class ACue_Ability_Loop_10186101 final : public AMarvelCueNotify_Ability
{
public:
	int32                                         CameraMoveAudio;                                   // 0x0E50(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_E54[0x4];                                      // 0x0E54(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"Cue_Ability_Loop_10186101">();
	}
	static class ACue_Ability_Loop_10186101* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACue_Ability_Loop_10186101>();
	}
};

// Class Hero_1018.Ability_101871
// 0x0008 (0x2590 - 0x2588)
class UAbility_101871 : public UAbility_108
{
public:
	uint8                                         Pad_2588[0x8];                                     // 0x2588(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"Ability_101871">();
	}
	static class UAbility_101871* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_101871>();
	}
};

// Class Hero_1018.Summoned_10187101
// 0x0010 (0x08A0 - 0x0890)
class ASummoned_10187101 : public AMarvelSummonerBase
{
public:
	class UCapsuleComponent*                      SoulCollision;                                     // 0x0890(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_898[0x8];                                      // 0x0898(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"Summoned_10187101">();
	}
	static class ASummoned_10187101* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASummoned_10187101>();
	}
};

// Class Hero_1018.SummonedMovementComponent_10187101
// 0x0010 (0x0A50 - 0x0A40)
class USummonedMovementComponent_10187101 final : public USummonedMovementComponent
{
public:
	float                                         DownTraceDistance;                                 // 0x0A40(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_A44[0xC];                                      // 0x0A44(0x000C)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"SummonedMovementComponent_10187101">();
	}
	static class USummonedMovementComponent_10187101* GetDefaultObj()
	{
		return GetDefaultObjImpl<USummonedMovementComponent_10187101>();
	}
};

// Class Hero_1018.SummonedComp_10187101
// 0x1050 (0x1CF0 - 0x0CA0)
class USummonedComp_10187101 : public UMarvelSummonedComponent
{
public:
	float                                         DamageRatio;                                       // 0x0CA0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_CA4[0x4];                                      // 0x0CA4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UCurveVector*                           SoulOffsetCurve;                                   // 0x0CA8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	struct FMarvelAbilityTraceContext             CollisionCheckContext;                             // 0x0CB0(0x0F90)(Edit, BlueprintVisible, ContainsInstancedReference, Protected, NativeAccessSpecifierProtected)
	float                                         CapsuleHalfHeightCut;                              // 0x1C40(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_1C44[0x4];                                     // 0x1C44(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPredictionKey                         UpdateOffsetKey;                                   // 0x1C48(0x00A0)(HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1CE8[0x8];                                     // 0x1CE8(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void UpdateSoulOffset(const struct FVector& OutValue);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"SummonedComp_10187101">();
	}
	static class USummonedComp_10187101* GetDefaultObj()
	{
		return GetDefaultObjImpl<USummonedComp_10187101>();
	}
};

// Class Hero_1018.EffectAbility_101871
// 0x0018 (0x1110 - 0x10F8)
class UEffectAbility_101871 final : public UMarvelEffectGameplayAbility
{
public:
	int32                                         SummonID;                                          // 0x10F8(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_10FC[0x4];                                     // 0x10FC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UAbility_101871*                        OwnAbility;                                        // 0x1100(0x0008)(ZeroConstructor, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class AMarvelBaseCharacter*                   SourceCharacter;                                   // 0x1108(0x0008)(ZeroConstructor, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)

public:
	void OnCharacterPreDeath(class AActor* InSourceAvatar, class AActor* InTargetAvatar, const struct FAttributeModifierHandle& ModifierParameterHandle);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"EffectAbility_101871">();
	}
	static class UEffectAbility_101871* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEffectAbility_101871>();
	}
};

// Class Hero_1018.MarvelCueNotify_101871_Actor
// 0x0070 (0x0D38 - 0x0CC8)
class AMarvelCueNotify_101871_Actor final : public AMarvelCueNotify_Actor
{
public:
	int32                                         CameraControlPriority;                             // 0x0CC8(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bEnableInterpSpringArmLength;                      // 0x0CCC(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_CCD[0x3];                                      // 0x0CCD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         SpringArmTargetLength;                             // 0x0CD0(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         SpringArmInterpInitSpeed;                          // 0x0CD4(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         SpringArmInterpMaxSpeed;                           // 0x0CD8(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         SpringArmInterpAcceleration;                       // 0x0CDC(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         SpringArmRecoveryInterpInitSpeed;                  // 0x0CE0(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         SpringArmRecoveryInterpMaxSpeed;                   // 0x0CE4(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         SpringArmRecoveryInterpAcceleration;               // 0x0CE8(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bEnableInterpSpringArmSocketOffset;                // 0x0CEC(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_CED[0x3];                                      // 0x0CED(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                SpringArmSocketOffset;                             // 0x0CF0(0x0018)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         SpringArmSocketInterpSpeed;                        // 0x0D08(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         SpringArmSocketInterpRecoverySpeed;                // 0x0D0C(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bEnableFOVInterp;                                  // 0x0D10(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_D11[0x3];                                      // 0x0D11(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         FOVTarget;                                         // 0x0D14(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         FOVInterpSpeed;                                    // 0x0D18(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         FOVInterpRecoverSpeed;                             // 0x0D1C(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UMaterialInstanceDynamic*               PPMInstanceDynamic;                                // 0x0D20(0x0008)(ZeroConstructor, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_D28[0x10];                                     // 0x0D28(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"MarvelCueNotify_101871_Actor">();
	}
	static class AMarvelCueNotify_101871_Actor* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMarvelCueNotify_101871_Actor>();
	}
};

// Class Hero_1018.Cue_Summoner_Loop_10187101
// 0x0060 (0x0EF0 - 0x0E90)
class ACue_Summoner_Loop_10187101 final : public AMarvelCueNotify_Summoned
{
public:
	class USkeletalMeshComponent*                 SkeletalMesh;                                      // 0x0E90(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class USkeletalMeshComponent*                 BoundSkeletalMesh;                                 // 0x0E98(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_EA0[0x50];                                     // 0x0EA0(0x0050)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void BindMeshMaterialVisibleChanged(class USkeletalMeshComponent* SkeletalMeshComponent);
	TArray<class FName> GetHideBones(class USkeletalMeshComponent* TargetMesh);
	void SetMaterialHidden(class USkeletalMeshComponent* SkeletalMeshComponent);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"Cue_Summoner_Loop_10187101">();
	}
	static class ACue_Summoner_Loop_10187101* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACue_Summoner_Loop_10187101>();
	}
};

// Class Hero_1018.Config_101881
// 0x00A0 (0x0138 - 0x0098)
class UConfig_101881 final : public UMarvelAbilityConfig
{
public:
	float                                         StartDecreasingAfterSeconds;                       // 0x0098(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         DarkManaDecreasingVelocity;                        // 0x009C(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         DarkManaMaxLimit;                                  // 0x00A0(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         DarkManaAfterReachMaxDecreasingVelocity;           // 0x00A4(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         DelayDecreasingTime;                               // 0x00A8(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_AC[0x4];                                       // 0x00AC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FAbilityManaConfig_101881>      DarkManaIncreasementConfig;                        // 0x00B0(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NativeAccessSpecifierPublic)
	struct FGameplayTagContainer                  BondAbilityTags;                                   // 0x00C0(0x0068)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, NativeAccessSpecifierPublic)
	float                                         BondAbilityManaIncreaseVelocity;                   // 0x0128(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bShouldTriggerFastDecreasingOnBondState;           // 0x012C(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bShouldTriggerDeBuffOnBondState;                   // 0x012D(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_12E[0x2];                                      // 0x012E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         EnergyMultiplierOnBondState;                       // 0x0130(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         DelayDecreasingTimeOnBondState;                    // 0x0134(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"Config_101881">();
	}
	static class UConfig_101881* GetDefaultObj()
	{
		return GetDefaultObjImpl<UConfig_101881>();
	}
};

// Class Hero_1018.Ability_101881
// 0x0148 (0x26C8 - 0x2580)
class UAbility_101881 : public UMarvelGameplayAbility
{
public:
	TMulticastInlineDelegate<void(float Value)>   DarkManaValueChangedDelegate;                      // 0x2580(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)
	EAbilityState_101881                          AbilityState;                                      // 0x2590(0x0001)(BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2591[0x7];                                     // 0x2591(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void()>              AbilityStateChangedDelegate;                       // 0x2598(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void()>              OnBondAbilityStateChanged;                         // 0x25A8(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	class UConfig_101881*                         Config;                                            // 0x25B8(0x0008)(ZeroConstructor, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_25C0[0x108];                                   // 0x25C0(0x0108)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void ApplyAntiHealBuff();
	void ClearDarkMana();
	float GetCurrentDarkMana();
	float GetCurrentManaPercentage();
	void OnAbilityDamage(class UGameplayAbility* Ability, const struct FAttributeModifierHandle& ModifierParameterHandle);
	void OnAbilityHit(class UGameplayAbility* Ability, const TArray<struct FHitResult>& HitResults);
	void OnAbilityStateUpdate();
	void OnBondAbilityTagUpdate(const struct FGameplayTag& Tag, bool TagExists);
	void OnManaAttributeChanged(class AActor* InSourceAvatar, const struct FAttributeModifierHandle& ModifierParameterHandle);
	void OnManaReachMax();
	void OnOwnerAbilityMissile(class UGameplayAbility* Ability);
	void OnOwnerActivateAbility(int32 AbilityID);
	void OnOwnerCharactorReborn(class AActor* TargetActor, const struct FCharacterRebornParam& Param);
	void OnOwnerDeath(class AActor* InSourceAvatar, class AActor* InTargetAvatar, const struct FAttributeModifierHandle& ModifierParameterHandle);
	void ServerClearDarkMana();
	void SetDarkManaValue(float InDarkManaValue);

	bool IsBondAbilityState() const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"Ability_101881">();
	}
	static class UAbility_101881* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_101881>();
	}
};

// Class Hero_1018.Cue_Ability_Loop_10188101
// 0x0148 (0x0F98 - 0x0E50)
class ACue_Ability_Loop_10188101 final : public AMarvelCueNotify_Ability
{
public:
	uint8                                         Pad_E50[0x8];                                      // 0x0E50(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         BeginAppearValue;                                  // 0x0E58(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_E5C[0x4];                                      // 0x0E5C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UCurveFloat*                            ManaCurveFloat;                                    // 0x0E60(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UCurveFloat*                            MaterialStartCurve;                                // 0x0E68(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UCurveFloat*                            MaterialEndCurve;                                  // 0x0E70(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UCurveFloat*                            MaterialIntervalCurve;                             // 0x0E78(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         MaterialStartAudioID;                              // 0x0E80(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         MaterialEndAudioID;                                // 0x0E84(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 RTPCAudioName;                                     // 0x0E88(0x0010)(Edit, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         TipsAudioID;                                       // 0x0E98(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         FullAudioID;                                       // 0x0E9C(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         TipsAudioTrigger;                                  // 0x0EA0(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	ECueAbilityState_101881                       EffectState;                                       // 0x0EA4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_EA5[0x3];                                      // 0x0EA5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class AMarvelBaseCharacter*                   MyCharacter;                                       // 0x0EA8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAbility_101881*                        Ability_101881;                                    // 0x0EB0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class USkeletalMeshComponent*                 CurrentMesh;                                       // 0x0EB8(0x0008)(ExportObject, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UCurveFloat*                            BondAbilitySwitchCurve;                            // 0x0EC0(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   CloakColorParameterName;                           // 0x0EC8(0x000C)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bHasBondAbility;                                   // 0x0ED4(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bTriggerFullAudio;                                 // 0x0ED5(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_ED6[0xC2];                                     // 0x0ED6(0x00C2)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void OnBondAbilityStateChanged();
	void OnBondAbilityTagUpdate(const struct FGameplayTag& Tag, bool TagExists);
	void OnChildActorResetMaterial();
	void OnCloakColorChanged(class FName TrackName, class FName PropertyName, float OutValue);
	void OnCloakColorChangedEnd();
	void OnDarkManaValueChanged(float ManaPercentage);
	void SetCloseState();
	void SetEndCenterEdgeMaterialValue(class FName TrackName, class FName PropertyName, float OutValue);
	void SetOpenState();
	void SetStartCenterEdgeMaterialValue(class FName TrackName, class FName PropertyName, float OutValue);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"Cue_Ability_Loop_10188101">();
	}
	static class ACue_Ability_Loop_10188101* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACue_Ability_Loop_10188101>();
	}
};

// Class Hero_1018.DoctorStrangeAnimInstance
// 0x0020 (0x0930 - 0x0910)
class UDoctorStrangeAnimInstance final : public UMarvelAnimInstance
{
public:
	bool                                          bIsFlying;                                         // 0x0910(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bIsFloating;                                       // 0x0911(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bIsDefending;                                      // 0x0912(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_913[0x1];                                      // 0x0913(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         AimOffsetAnimIndex;                                // 0x0914(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bFloatDefending;                                   // 0x0918(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_919[0x3];                                      // 0x0919(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         VFloatForward;                                     // 0x091C(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         VFloatRight;                                       // 0x0920(0x0004)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bKnockWhenDefence;                                 // 0x0924(0x0001)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_925[0xB];                                      // 0x0925(0x000B)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"DoctorStrangeAnimInstance">();
	}
	static class UDoctorStrangeAnimInstance* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDoctorStrangeAnimInstance>();
	}
};

// Class Hero_1018.DoctorStrangeChildActor
// 0x0020 (0x0A80 - 0x0A60)
class ADoctorStrangeChildActor final : public AMarvelCharacterChildActor
{
public:
	class UPhysicalAnimationComponent*            PhysicalAnimation;                                 // 0x0A60(0x0008)(Edit, BlueprintVisible, ExportObject, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class FName>                           BoneName;                                          // 0x0A68(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NativeAccessSpecifierPublic)
	uint8                                         Pad_A78[0x8];                                      // 0x0A78(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void SetPhysicalAnimation();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"DoctorStrangeChildActor">();
	}
	static class ADoctorStrangeChildActor* GetDefaultObj()
	{
		return GetDefaultObjImpl<ADoctorStrangeChildActor>();
	}
};

// Class Hero_1018.DoctorStrangeCharacter
// 0x0080 (0x1890 - 0x1810)
class ADoctorStrangeCharacter : public AMarvelBaseCharacter
{
public:
	bool                                          bIsDefending;                                      // 0x1810(0x0001)(BlueprintVisible, BlueprintReadOnly, Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIsFlying;                                         // 0x1811(0x0001)(BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIsFloating;                                       // 0x1812(0x0001)(BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1813[0x1];                                     // 0x1813(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CurrentPitch;                                      // 0x1814(0x0004)(BlueprintVisible, BlueprintReadOnly, Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UDoctorStrangeMoveLogicBaseComponent*   DoctorStrangeMoveLogic;                            // 0x1818(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, EditConst, InstancedReference, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UMarvelMultiCapsuleComponent*           ShieldCollision;                                   // 0x1820(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, EditConst, InstancedReference, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_1828[0x68];                                    // 0x1828(0x0068)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void OnTagUpdate(const struct FGameplayTag& Tag, bool bTagExists);
	void SetIsDefending(bool bInShield);
	void SetIsFloating(bool bIsFloating_0);
	void SetIsFlying(bool bFlying);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"DoctorStrangeCharacter">();
	}
	static class ADoctorStrangeCharacter* GetDefaultObj()
	{
		return GetDefaultObjImpl<ADoctorStrangeCharacter>();
	}
};

// Class Hero_1018.DoctorStrangeMoveLogicBaseComponent
// 0x0008 (0x03F8 - 0x03F0)
class UDoctorStrangeMoveLogicBaseComponent final : public UMarvelMoveLogicBaseComponent
{
public:
	TWeakObjectPtr<class AMovingCameraActor>      LandscapeCamera;                                   // 0x03F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"DoctorStrangeMoveLogicBaseComponent">();
	}
	static class UDoctorStrangeMoveLogicBaseComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDoctorStrangeMoveLogicBaseComponent>();
	}
};

// Class Hero_1018.DoctorStrangeMovementComponent
// 0x0000 (0x1B60 - 0x1B60)
class UDoctorStrangeMovementComponent final : public UMarvelCharacterMovementComponent
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"DoctorStrangeMovementComponent">();
	}
	static class UDoctorStrangeMovementComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDoctorStrangeMovementComponent>();
	}
};

// Class Hero_1018.EpicMomentAction_1018
// 0x0050 (0x0170 - 0x0120)
class UEpicMomentAction_1018 : public UEpicMomentBaseAction
{
public:
	uint8                                         Pad_120[0x28];                                     // 0x0120(0x0028)(Fixing Size After Last Property [ Dumper-7 ])
	struct FEpicMomentNodeInfo                    QConfig;                                           // 0x0148(0x000C)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, NoDestructor, NativeAccessSpecifierPublic)
	struct FEpicMomentNodeInfo                    ShieldBlockConfig;                                 // 0x0154(0x000C)(Edit, BlueprintVisible, BlueprintReadOnly, DisableEditOnInstance, NoDestructor, NativeAccessSpecifierPublic)
	int32                                         QBuffID;                                           // 0x0160(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         QBuffCount;                                        // 0x0164(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ShieldSummonerID;                                  // 0x0168(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ShieldSummonerBlockDamageThreshold;                // 0x016C(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void OnActorTakeDamage(class AActor* Instigator, class AActor* Target, const struct FAttributeModifierHandle& ModifierParameterHandle, const struct FGlobalEventExtraData& ExtraData);
	void OnGameplayEffectAppliedToTarget(class UAbilitySystemComponent* ASC, const struct FGameplayEffectSpecStackHandle& GameplayEffectSpecHandle, const struct FActiveGameplayEffectHandle& ActiveGameplayEffectHandle);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"EpicMomentAction_1018">();
	}
	static class UEpicMomentAction_1018* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEpicMomentAction_1018>();
	}
};

// Class Hero_1018.LevelCheckPenetrationPortalInterface
// 0x0000 (0x0030 - 0x0030)
class ILevelCheckPenetrationPortalInterface final : public ILevelCheckPenetrationActorInterface
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"LevelCheckPenetrationPortalInterface">();
	}
	static class ILevelCheckPenetrationPortalInterface* GetDefaultObj()
	{
		return GetDefaultObjImpl<ILevelCheckPenetrationPortalInterface>();
	}
};

// Class Hero_1018.TabData_1018
// 0x0000 (0x0050 - 0x0050)
class UTabData_1018 : public UHeroTabDataBase
{
public:
	void OnActorPreDeath(class AActor* Killer, class AActor* Target, const struct FAttributeModifierHandle& ModifierParameterHandle, const struct FGlobalEventExtraData& ExtraData);
	void OnActorTakeDamage(class AActor* Instigator, class AActor* Target, const struct FAttributeModifierHandle& ModifierParameterHandle, const struct FGlobalEventExtraData& ExtraData);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"TabData_1018">();
	}
	static class UTabData_1018* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTabData_1018>();
	}
};

}

