#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ItemSpray_LightBP

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ItemSpray_LightBP.ItemSpray_LightBP_C
// 0x0018 (0x04A8 - 0x0490)
class AItemSpray_LightBP_C final : public AActor
{
public:
	class UDirectionalLightComponent*             Rim_Light_Spray;                                   // 0x0490(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDirectionalLightComponent*             Main_Light_Spray;                                  // 0x0498(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        Scene;                                             // 0x04A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ItemSpray_LightBP_C">();
	}
	static class AItemSpray_LightBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AItemSpray_LightBP_C>();
	}
};

}

