#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: JarvisReplay

#include "Basic.hpp"

#include "Engine_classes.hpp"
#include "OnlineSubsystemUtils_classes.hpp"
#include "CoreUObject_classes.hpp"


namespace SDK
{

// Class JarvisReplay.JarvisDemoNetConnection
// 0x0000 (0x21E8 - 0x21E8)
class UJarvisDemoNetConnection final : public UDemoNetConnection
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"JarvisDemoNetConnection">();
	}
	static class UJarvisDemoNetConnection* GetDefaultObj()
	{
		return GetDefaultObjImpl<UJarvisDemoNetConnection>();
	}
};

// Class JarvisReplay.JarvisReplayCharacter
// 0x0010 (0x0A20 - 0x0A10)
class AJarvisReplayCharacter final : public ACharacter
{
public:
	class UInputMappingContext*                   DefaultMappingContext;                             // 0x0A10(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_A18[0x8];                                      // 0x0A18(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"JarvisReplayCharacter">();
	}
	static class AJarvisReplayCharacter* GetDefaultObj()
	{
		return GetDefaultObjImpl<AJarvisReplayCharacter>();
	}
};

// Class JarvisReplay.JarvisReplayCharacterInterface
// 0x0000 (0x0030 - 0x0030)
class IJarvisReplayCharacterInterface final : public IInterface
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"JarvisReplayCharacterInterface">();
	}
	static class IJarvisReplayCharacterInterface* GetDefaultObj()
	{
		return GetDefaultObjImpl<IJarvisReplayCharacterInterface>();
	}
};

// Class JarvisReplay.JarvisReplayComponent
// 0x0028 (0x0118 - 0x00F0)
class UJarvisReplayComponent final : public UActorComponent
{
public:
	uint8                                         Pad_F0[0x28];                                      // 0x00F0(0x0028)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void PlayRecord();
	void StartRecord();
	void StopRecord();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"JarvisReplayComponent">();
	}
	static class UJarvisReplayComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UJarvisReplayComponent>();
	}
};

// Class JarvisReplay.JarvisReplayConnection
// 0x0010 (0x2250 - 0x2240)
class UJarvisReplayConnection final : public UIpConnection
{
public:
	uint8                                         Pad_2240[0x10];                                    // 0x2240(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"JarvisReplayConnection">();
	}
	static class UJarvisReplayConnection* GetDefaultObj()
	{
		return GetDefaultObjImpl<UJarvisReplayConnection>();
	}
};

// Class JarvisReplay.JarvisReplayGameInstance
// 0x0000 (0x0340 - 0x0340)
class UJarvisReplayGameInstance final : public UPlatformGameInstance
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"JarvisReplayGameInstance">();
	}
	static class UJarvisReplayGameInstance* GetDefaultObj()
	{
		return GetDefaultObjImpl<UJarvisReplayGameInstance>();
	}
};

// Class JarvisReplay.JarvisReplayLibrary
// 0x0000 (0x0030 - 0x0030)
class UJarvisReplayLibrary final : public UBlueprintFunctionLibrary
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"JarvisReplayLibrary">();
	}
	static class UJarvisReplayLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<UJarvisReplayLibrary>();
	}
};

// Class JarvisReplay.JarvisReplayNetDriver
// 0x0040 (0x0BD0 - 0x0B90)
class UJarvisReplayNetDriver final : public UIpNetDriver
{
public:
	uint8                                         Pad_B90[0x40];                                     // 0x0B90(0x0040)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"JarvisReplayNetDriver">();
	}
	static class UJarvisReplayNetDriver* GetDefaultObj()
	{
		return GetDefaultObjImpl<UJarvisReplayNetDriver>();
	}
};

// Class JarvisReplay.JarvisReplayPlayerController
// 0x0000 (0x0A98 - 0x0A98)
class AJarvisReplayPlayerController final : public APlayerController
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"JarvisReplayPlayerController">();
	}
	static class AJarvisReplayPlayerController* GetDefaultObj()
	{
		return GetDefaultObjImpl<AJarvisReplayPlayerController>();
	}
};

// Class JarvisReplay.JarvisReplayDemoNetDriver
// 0x0030 (0x1AA0 - 0x1A70)
class UJarvisReplayDemoNetDriver : public UDemoNetDriver
{
public:
	uint8                                         Pad_1A70[0x30];                                    // 0x1A70(0x0030)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"JarvisReplayDemoNetDriver">();
	}
	static class UJarvisReplayDemoNetDriver* GetDefaultObj()
	{
		return GetDefaultObjImpl<UJarvisReplayDemoNetDriver>();
	}
};

// Class JarvisReplay.JarvisReplaySubsystem
// 0x0068 (0x00B0 - 0x0048)
class UJarvisReplaySubsystem final : public UReplaySubsystem
{
public:
	uint8                                         Pad_48[0x68];                                      // 0x0048(0x0068)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void LocalRecordJarvisReplay(const class FString& Name_0, const class FString& FriendlyName);
	void PlayJarvisReplay(const class FString& DemoURL, bool bIsNetFile);
	void PlayJarvisReplaySequence(const TArray<class FString>& ReplayIDSequence, int32 InLoopTimes, float InReplayInterval, bool bInQuitAppOnEnd);
	void RecordJarvisReplay();

	void CopyReplayIDToClipboard() const;
	float GetRecordingDemoCurrentTime() const;
	class FString GetRecordingReplayID() const;
	bool IsJarvisRecording() const;
	void UploadReplayFile() const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"JarvisReplaySubsystem">();
	}
	static class UJarvisReplaySubsystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<UJarvisReplaySubsystem>();
	}
};

}

