#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: KnockUp_102972

#include "Basic.hpp"

#include "PyAbility_102972_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass KnockUp_102972.KnockUp_102972_C
// 0x0000 (0x1DA0 - 0x1DA0)
class UKnockUp_102972_C final : public UPyKnockUp_102972
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"KnockUp_102972_C">();
	}
	static class UKnockUp_102972_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKnockUp_102972_C>();
	}
};

}

