#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: KnockUp_10406101

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass KnockUp_10406101.KnockUp_10406101_C
// 0x0000 (0x1D98 - 0x1D98)
class UKnockUp_10406101_C final : public UMarvelKnockUpAbility
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"KnockUp_10406101_C">();
	}
	static class UKnockUp_10406101_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UKnockUp_10406101_C>();
	}
};

}

