#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LimitTimeTrain

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// PythonClass LimitTimeTrain.UISettingEntryLimitTimeTrainHandler
// 0x0000 (0x0030 - 0x0030)
class UUISettingEntryLimitTimeTrainHandler final : public UUISettingEntrySettingHandler
{
public:
	float BP_GetCurrentValue(class UObject* Obj, const class FString& setting_key, const TMap<class FString, class FString>& P, const TMap<int32, class FText>& O);
	float BP_GetDefaultValue(class UObject* Obj, const class FString& setting_key, const TMap<class FString, class FString>& P, const TMap<int32, class FText>& O);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"UISettingEntryLimitTimeTrainHandler">();
	}
	static class UUISettingEntryLimitTimeTrainHandler* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUISettingEntryLimitTimeTrainHandler>();
	}
};

}

