#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MarvelHonorBadge_BP

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK
{

// UserDefinedStruct MarvelHonorBadge_BP.MarvelHonorBadge_BP
// 0x0028 (0x0028 - 0x0000)
struct FMarvelHonorBadge_BP final
{
public:
	class UTexture*                               Icon_8_0DF2BC6D4412D9AEC777DC9D29C33AF3;           // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UTexture*                               BigIcon_15_29FEC41648BB4031E08CE882EEF7C31A;       // 0x0008(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FDataTableRowHandle                    Season_24_DC036A0848D80855915FA7B6E673434C;        // 0x0010(0x0018)(Edit, BlueprintVisible, NoDestructor)
};

}

