#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MarvelAISystemBP

#include "Basic.hpp"

#include "PyMarvelAISystem_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass MarvelAISystemBP.MarvelAISystemBP_C
// 0x0000 (0x02C8 - 0x02C8)
class UMarvelAISystemBP_C final : public UPyMarvelAISystem
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MarvelAISystemBP_C">();
	}
	static class UMarvelAISystemBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMarvelAISystemBP_C>();
	}
};

}

