#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NotTreatShield_102661

#include "Basic.hpp"

#include "PyAbility_102661_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass NotTreatShield_102661.NotTreatShield_102661_C
// 0x0000 (0x12B8 - 0x12B8)
class UNotTreatShield_102661_C final : public UPyFallability_10266101
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"NotTreatShield_102661_C">();
	}
	static class UNotTreatShield_102661_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNotTreatShield_102661_C>();
	}
};

}

