#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PlacedPortalActor_101861_BP

#include "Basic.hpp"

#include "Hero_1018_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PlacedPortalActor_101861_BP.PlacedPortalActor_101861_BP_C
// 0x0000 (0x0750 - 0x0750)
class APlacedPortalActor_101861_BP_C final : public APlacedPortalActor_101861
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PlacedPortalActor_101861_BP_C">();
	}
	static class APlacedPortalActor_101861_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APlacedPortalActor_101861_BP_C>();
	}
};

}

