#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Projectile_10302101_BP

#include "Basic.hpp"

#include "Hero_1030_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Projectile_10302101_BP.Projectile_10302101_BP_C
// 0x0000 (0x40A0 - 0x40A0)
class AProjectile_10302101_BP_C : public AProjectile_10302101
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Projectile_10302101_BP_C">();
	}
	static class AProjectile_10302101_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AProjectile_10302101_BP_C>();
	}
};

}

