#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_102302

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// PythonClass PyAbility_102302.PyAbility_102302
// 0x0000 (0x2588 - 0x2588)
class UPyAbility_102302 : public UAbility_102
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyAbility_102302">();
	}
	static class UPyAbility_102302* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyAbility_102302>();
	}
};

}

