#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_104013

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// PythonClass PyAbility_104013.PyConfig_104013
// 0x0018 (0x00B0 - 0x0098)
class UPyConfig_104013 final : public UMarvelAbilityConfig
{
public:
	float                                         RefreshDelay;                                      // 0x0098(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_9C[0x4];                                       // 0x009C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TSubclassOf<class ULegacyCameraShake>         HitCameraShakeClass;                               // 0x00A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ScopeId;                                           // 0x00A8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyConfig_104013">();
	}
	static class UPyConfig_104013* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyConfig_104013>();
	}
};

// PythonClass PyAbility_104013.PyAbility_104013
// 0x0000 (0x2588 - 0x2588)
class UPyAbility_104013 : public UAbility_108
{
public:
	void BeginPlay();
	bool CanActivate();
	void K2_ActivateAbility();
	void OnAbilityHit(class UGameplayAbility* Ability, const TArray<struct FHitResult>& Result);
	void MissileEventNotify();
	void OnNoActorScopeInited(class UMarvelAgentTraceComponent* TraceComp, class UMarvelAgentEffectiveComponent* EffectComp);
	void BreakEventNotify();
	void K2_OnEndAbility(bool bWasCancelled);
	void NativeOnMontageCompleted(const class FString& Tag);
	void NativeOnMontageInterrupted(const class FString& Tag);
	void NativeOnMontageCancelled(const class FString& Tag);
	void NativeOnMontageEvent(const class FString& Tag);
	void EndPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyAbility_104013">();
	}
	static class UPyAbility_104013* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyAbility_104013>();
	}
};

// PythonClass PyAbility_104013.PyEffectiveComponent_10401301
// 0x0000 (0x1C00 - 0x1C00)
class UPyEffectiveComponent_10401301 final : public UMarvelAgentEffectiveComponent
{
public:
	void K2_OnInitialized();
	TArray<struct FHitResult> K2_OnPreApplyContainer(const TArray<struct FHitResult>& HitResults);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyEffectiveComponent_10401301">();
	}
	static class UPyEffectiveComponent_10401301* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyEffectiveComponent_10401301>();
	}
};

// PythonClass PyAbility_104013.PyCue_Ability_Instant_10401301
// 0x0010 (0x0378 - 0x0368)
class UPyCue_Ability_Instant_10401301 final : public UMarvelCueNotify_Base
{
public:
	class UFXSystemAsset*                         AttackFXAsset;                                     // 0x0368(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bAttachToRoot;                                     // 0x0370(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	bool OnExecute(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters) const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyCue_Ability_Instant_10401301">();
	}
	static class UPyCue_Ability_Instant_10401301* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyCue_Ability_Instant_10401301>();
	}
};

}

