#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_103614

#include "Basic.hpp"

#include "PyCue_AbilityLoop_Cable_Base_classes.hpp"
#include "Marvel_structs.hpp"
#include "Marvel_classes.hpp"
#include "Hero_1036_structs.hpp"
#include "Hero_1036_classes.hpp"
#include "GameplayTags_structs.hpp"


namespace SDK
{

// PythonClass PyAbility_103614.PyConfig_103614
// 0x37A0 (0x3840 - 0x00A0)
class UPyConfig_103614 final : public UConfig_103614
{
public:
	struct FSelectTaskParam                       SelectParam;                                       // 0x00A0(0x10A0)(Edit, BlueprintVisible, DisableEditOnInstance, NativeAccessSpecifierPublic)
	struct FDashAbilityInfo                       DashInfo;                                          // 0x1140(0x0BA8)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	struct FDashAbilityInfo                       DashBackInfo;                                      // 0x1CE8(0x0BA8)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	struct FMarvelAbilityTraceContext             TraceContext;                                      // 0x2890(0x0F90)(Edit, BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
	struct FGameplayTag                           ScreenCueTag;                                      // 0x3820(0x000C)(Edit, BlueprintVisible, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         KickDamage;                                        // 0x382C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         EnhancedKickDamage;                                // 0x3830(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyConfig_103614">();
	}
	static class UPyConfig_103614* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyConfig_103614>();
	}
};

// PythonClass PyAbility_103614.PyCue_Buff_10361402
// 0x0018 (0x1050 - 0x1038)
class APyCue_Buff_10361402 final : public AMarvelCueNotify_Buff
{
public:
	int32                                         HitAudioID;                                        // 0x1038(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         AbilityID;                                         // 0x103C(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UFXSystemAsset*                         NormalFX;                                          // 0x1040(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UFXSystemAsset*                         EnhancedFX;                                        // 0x1048(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void OnActiveFX(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);
	void WhileActiveFX(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyCue_Buff_10361402">();
	}
	static class APyCue_Buff_10361402* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyCue_Buff_10361402>();
	}
};

// PythonClass PyAbility_103614.PyCue_AbilityLoop_103614
// 0x0020 (0x1180 - 0x1160)
class APyCue_AbilityLoop_103614 final : public APyCue_AbilityLoop_Cable_Base
{
public:
	float                                         TimeToShootCable;                                  // 0x1160(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         TimeToBreakRightHand;                              // 0x1164(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         TimeToBreakCableHead;                              // 0x1168(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         CableFlySpeed;                                     // 0x116C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UFXSystemAsset*                         HitFX;                                             // 0x1170(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         HitAudioID;                                        // 0x1178(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void ResetDefault();
	bool WhileActive(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);
	bool OnRemove(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);
	void K2_ListenProjectileSpawnAndHit();
	void K2_UnlistenProjectileSpawnAndHit();
	void OnAbilityState103614Changed(EAbilityState103614 AbilityState);
	void OnTimeToShootCable();
	void K2_OnCableHit(const struct FVector& HitLocation);
	void OnTimeToBreakRightHand();
	void OnTimeToBreakCableHead();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyCue_AbilityLoop_103614">();
	}
	static class APyCue_AbilityLoop_103614* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyCue_AbilityLoop_103614>();
	}
};

// PythonClass PyAbility_103614.PyAbility_103614
// 0x0000 (0x25A0 - 0x25A0)
class UPyAbility_103614 : public UAbility_103614
{
public:
	void BeginPlay();
	bool TryMakeTriggerContext(struct FGameplayEventData& EventData);
	bool CanActivate();
	void K2_ActivateAbility();
	void K2_ActivateAbilityFromEvent(const struct FGameplayEventData& EventData);
	void K2_OnEndAbility(bool bWasCancelled);
	void MissileEventNotify();
	void NativeOnMontageEvent(const class FString& Tag);
	void ServerReceiveKnockUpDirection(const struct FVector& Dir);
	void NativeOnMontageCompleted(const class FString& Tag);
	void K2_ReadyToRecovery();
	void OnDashFinish(EDashStopReason Reason);
	void DashBackAfterRecorery();
	class AActor* GetTargetActor();
	class AActor* GetTarget();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyAbility_103614">();
	}
	static class UPyAbility_103614* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyAbility_103614>();
	}
};

}

