#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_102461

#include "Basic.hpp"

#include "Marvel_classes.hpp"
#include "Hero_1024_classes.hpp"


namespace SDK
{

// PythonClass PyAbility_102461.PyProjectile_102461
// 0x0010 (0x3060 - 0x3050)
class APyProjectile_102461 : public AMarvelAbilityTargetActor_Projectile
{
public:
	int32                                         ScopeId;                                           // 0x3050(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void K2_OnBeginAgentTask();
	void K2_OnFlyOverMaxDistance(const struct FHitResult& HitResult);
	void K2_OnProcessHit(const struct FHitResult& ImpactResult);
	void K2_OnEndAgentTask();
	void K2_OnProjectileInfoForceChanged_ThreadSafe(const struct FProjectileForceChangedInfo& InProjectileForceChangedInfo);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyProjectile_102461">();
	}
	static class APyProjectile_102461* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyProjectile_102461>();
	}
};

// PythonClass PyAbility_102461.PyScope_10246101
// 0x0010 (0x1710 - 0x1700)
class APyScope_10246101 final : public AMarvelAbilityTargetActor_Scope
{
public:
	int32                                         BuffID;                                            // 0x1700(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void K2_OnBeginAgentTask();
	void OnTraceResults(const TArray<struct FHitResult>& HitResults);
	void K2_OnEndAgentTask();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyScope_10246101">();
	}
	static class APyScope_10246101* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyScope_10246101>();
	}
};

// PythonClass PyAbility_102461.PyConfig_102461
// 0x0008 (0x0C48 - 0x0C40)
class UPyConfig_102461 final : public UConfig_102461
{
public:
	int32                                         ProjectileID;                                      // 0x0C40(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyConfig_102461">();
	}
	static class UPyConfig_102461* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyConfig_102461>();
	}
};

// PythonClass PyAbility_102461.PyAbility_102461
// 0x0010 (0x2598 - 0x2588)
class UPyAbility_102461 : public UAbility_108
{
public:
	TMulticastInlineDelegate<void(TArray<class AActor*>& TargetList)> OnSoulLinkEnemy;                                   // 0x2588(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)

public:
	void BeginPlay();
	void NativeOnMontageInterrupted(const class FString& Tag);
	void NativeOnMontageCancelled(const class FString& Tag);
	void HandleAnimSocketInfo(int32 SocketId, const struct FMarvelAbilitySocketInfo& SocketInfo);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyAbility_102461">();
	}
	static class UPyAbility_102461* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyAbility_102461>();
	}
};

// PythonClass PyAbility_102461.PyCue_Buff_10246103
// 0x0018 (0x1050 - 0x1038)
class APyCue_Buff_10246103 final : public AMarvelCueNotify_Buff
{
public:
	class UFXSystemAsset*                         LinkLineFXAsset;                                   // 0x1038(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FName                                   LinkLineFXPramName;                                // 0x1040(0x000C)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void WhileActiveFX(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);
	void OnRemoveFX(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyCue_Buff_10246103">();
	}
	static class APyCue_Buff_10246103* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyCue_Buff_10246103>();
	}
};

// PythonClass PyAbility_102461.PyCue_Projectile_Loop_10246101
// 0x0020 (0x0DD0 - 0x0DB0)
class APyCue_Projectile_Loop_10246101 final : public AMarvelCueNotify_Projectile
{
public:
	class UFXSystemAsset*                         GroundFX;                                          // 0x0DB0(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class AActor*>                         Ignores;                                           // 0x0DB8(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
	float                                         DecalCheckHeight;                                  // 0x0DC8(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void OnExecuteFX(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyCue_Projectile_Loop_10246101">();
	}
	static class APyCue_Projectile_Loop_10246101* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyCue_Projectile_Loop_10246101>();
	}
};

}

