#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_101462

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// PythonClass PyAbility_101462.PyAbility_101462
// 0x0008 (0x25D0 - 0x25C8)
class UPyAbility_101462 : public UAbility_105
{
public:
	bool                                          IsTurretFiring;                                    // 0x25C8(0x0001)(BlueprintVisible, BlueprintReadOnly, Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void BeginPlay();
	bool CanActivate();
	void K2_ActivateAbility();
	void K2_OnEndAbility(bool Cancel);
	void OnRep_IsTurretFiring();
	void OnPressFireInput(float ElapsedTime);
	void OnReleaseFireInput(float ElapsedTime);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyAbility_101462">();
	}
	static class UPyAbility_101462* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyAbility_101462>();
	}
};

}

