#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_101652

#include "Basic.hpp"


namespace SDK::Params
{

// PythonFunction PyAbility_101652.PyAbility_101652.K2_OnEndAbility
// 0x0001 (0x0001 - 0x0000)
struct PyAbility_101652_K2_OnEndAbility final
{
public:
	bool                                          bWasCancelled;                                     // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// PythonFunction PyAbility_101652.PyAbility_101652.NativeOnMontageCompleted
// 0x0010 (0x0010 - 0x0000)
struct PyAbility_101652_NativeOnMontageCompleted final
{
public:
	class FString                                 Tag;                                               // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash)
};

// PythonFunction PyAbility_101652.PyAbility_101652.NativeOnMontageBlendOut
// 0x0010 (0x0010 - 0x0000)
struct PyAbility_101652_NativeOnMontageBlendOut final
{
public:
	class FString                                 Tag;                                               // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash)
};

// PythonFunction PyAbility_101652.PyAbility_101652.NativeOnMontageInterrupted
// 0x0010 (0x0010 - 0x0000)
struct PyAbility_101652_NativeOnMontageInterrupted final
{
public:
	class FString                                 Tag;                                               // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash)
};

// PythonFunction PyAbility_101652.PyAbility_101652.NativeOnMontageCancelled
// 0x0010 (0x0010 - 0x0000)
struct PyAbility_101652_NativeOnMontageCancelled final
{
public:
	class FString                                 Tag;                                               // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash)
};

}

