#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_102322

#include "Basic.hpp"

#include "Hero_1023_classes.hpp"


namespace SDK
{

// PythonClass PyAbility_102322.PyConfig_102322
// 0x0000 (0x00E8 - 0x00E8)
class UPyConfig_102322 final : public UConfig_102322
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyConfig_102322">();
	}
	static class UPyConfig_102322* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyConfig_102322>();
	}
};

// PythonClass PyAbility_102322.PyAbility_102322
// 0x0000 (0x26A8 - 0x26A8)
class UPyAbility_102322 : public UAbility_102322
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyAbility_102322">();
	}
	static class UPyAbility_102322* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyAbility_102322>();
	}
};

}

