#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_103811

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// PythonClass PyAbility_103811.PyAbility_103811
// 0x0000 (0x2588 - 0x2588)
class UPyAbility_103811 : public UAbility_108
{
public:
	void K2_ActivateAbility();
	void K2_OnEndAbility(bool bWasCancelled);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyAbility_103811">();
	}
	static class UPyAbility_103811* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyAbility_103811>();
	}
};

}

