#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_101141

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// PythonClass PyAbility_101141.PySummonedComp_10114101
// 0x0000 (0x0D10 - 0x0D10)
class UPySummonedComp_10114101 final : public UProtectiveSummonedComponent
{
public:
	void K2_OnBeginAgentTask();
	void K2_OnEndAgentTask();
	void K2_OnSummonedTakeDamage(class AActor* InSourceAvatar, class AActor* InTargetAvatar, const struct FAttributeModifierHandle& ModifierHandle);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PySummonedComp_10114101">();
	}
	static class UPySummonedComp_10114101* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPySummonedComp_10114101>();
	}
};

// PythonClass PyAbility_101141.PyCue_Summoner_Loop_10114101
// 0x0008 (0x0E98 - 0x0E90)
class APyCue_Summoner_Loop_10114101 final : public AMarvelCueNotify_Summoned
{
public:
	int32                                         ShieldHalfBreakAudioID;                            // 0x0E90(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         ShieldRadiusFactor;                                // 0x0E94(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void PlayShieldHalfBreakAudio(class AActor* InSourceAvatar, class AActor* InTargetAvatar, const struct FAttributeModifierHandle& ModifierParameterHandle);
	void WhileActiveFX(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);
	void OnRemoveFX(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyCue_Summoner_Loop_10114101">();
	}
	static class APyCue_Summoner_Loop_10114101* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyCue_Summoner_Loop_10114101>();
	}
};

}

