#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_103721

#include "Basic.hpp"

#include "Marvel_classes.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK
{

// PythonClass PyAbility_103721.PyConfig_103721
// 0x0018 (0x00B0 - 0x0098)
class UPyConfig_103721 final : public UMarvelAbilityConfig
{
public:
	struct FVector                                FirePointLocationOffset;                           // 0x0098(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyConfig_103721">();
	}
	static class UPyConfig_103721* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyConfig_103721>();
	}
};

// PythonClass PyAbility_103721.PyUIController_103721
// 0x0008 (0x0C68 - 0x0C60)
class UPyUIController_103721 final : public UUIC_Ability
{
public:
	class UTexture2D*                             Icon;                                              // 0x0C60(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void OnInit();
	void OnDestruct();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyUIController_103721">();
	}
	static class UPyUIController_103721* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyUIController_103721>();
	}
};

// PythonClass PyAbility_103721.PyAbility_103721
// 0x0008 (0x2588 - 0x2580)
class UPyAbility_103721 : public UMarvelGameplayAbility
{
public:
	int32                                         ShootIronCount;                                    // 0x2580(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void BeginPlay();
	bool CanActivate();
	void K2_ActivateAbility();
	void HandleAnimSocketInfo(int32 SocketId, const struct FMarvelAbilitySocketInfo& SocketInfo);
	void BreakEventNotify();
	void K2_OnEndAbility(bool bWasCancelled);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyAbility_103721">();
	}
	static class UPyAbility_103721* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyAbility_103721>();
	}
};

// PythonClass PyAbility_103721.PyCue_Projectile_Loop_10372100
// 0x0000 (0x0DB0 - 0x0DB0)
class APyCue_Projectile_Loop_10372100 final : public AMarvelCueNotify_Projectile
{
public:
	void WhileActiveFX(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);
	void OnExecuteFX(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);
	void OnExecuteForceEndFX(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyCue_Projectile_Loop_10372100">();
	}
	static class APyCue_Projectile_Loop_10372100* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyCue_Projectile_Loop_10372100>();
	}
};

// PythonClass PyAbility_103721.PyCue_Ability_Loop_10372101
// 0x0058 (0x0EA8 - 0x0E50)
class APyCue_Ability_Loop_10372101 final : public AMarvelCueNotify_Ability
{
public:
	class UFXSystemAsset*                         AggregationFX1;                                    // 0x0E50(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UFXSystemAsset*                         AggregationFX2;                                    // 0x0E58(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UFXSystemAsset*                         AggregationFX3;                                    // 0x0E60(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                FXReletiveLocation;                                // 0x0E68(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FRotator                               FXReletiveRotation;                                // 0x0E80(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	int32                                         AudioID1;                                          // 0x0E98(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         AudioID2;                                          // 0x0E9C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         AudioID3;                                          // 0x0EA0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void WhileActiveFX(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);
	void WhileActiveAudio(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);
	void OnExecuteFX(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);
	void OnRemoveFX(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyCue_Ability_Loop_10372101">();
	}
	static class APyCue_Ability_Loop_10372101* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyCue_Ability_Loop_10372101>();
	}
};

}

