#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyDoctorStrangeCharacter

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// PythonFunction PyDoctorStrangeCharacter.PyDoctorStrangeCharacter.BindOnLandAudioEvent
// 0x0004 (0x0004 - 0x0000)
struct PyDoctorStrangeCharacter_BindOnLandAudioEvent final
{
public:
	int32                                         AudioID;                                           // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// PythonFunction PyDoctorStrangeCharacter.PyDoctorStrangeCharacter.OnLandedCallback
// 0x0170 (0x0170 - 0x0000)
struct PyDoctorStrangeCharacter_OnLandedCallback final
{
public:
	struct FHitResult                             Hit;                                               // 0x0000(0x0170)(ConstParm, Parm, OutParm, ReferenceParm)
};

}

