#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyKrakoaPortal

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// PythonFunction PyKrakoaPortal.PyKrakoaPortal.ReceiveEndPlay
// 0x0001 (0x0001 - 0x0000)
struct PyKrakoaPortal_ReceiveEndPlay final
{
public:
	EEndPlayReason                                EndPlayReason;                                     // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// PythonFunction PyKrakoaPortal.PyKrakoaPortal.CheckTeleportFinish
// 0x0020 (0x0020 - 0x0000)
struct PyKrakoaPortal_CheckTeleportFinish final
{
public:
	class AMarvelBaseCharacter*                   Character;                                         // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FVector                                target_pos;                                        // 0x0008(0x0018)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// PythonFunction PyKrakoaPortal.PyKrakoaPortal.OpenAndClose
// 0x0001 (0x0001 - 0x0000)
struct PyKrakoaPortal_OpenAndClose final
{
public:
	bool                                          Open;                                              // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

