#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyLevelTeamKillAudioComponent

#include "Basic.hpp"

#include "PyModeAudioComponent_classes.hpp"
#include "MarvelLevel_structs.hpp"
#include "MarvelLevel_classes.hpp"


namespace SDK
{

// PythonClass PyLevelTeamKillAudioComponent.PyLevelTeamKillAudioComponent
// 0x0000 (0x0108 - 0x0108)
class UPyLevelTeamKillAudioComponent final : public UPyModeAudioComponent
{
public:
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyLevelTeamKillAudioComponent">();
	}
	static class UPyLevelTeamKillAudioComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyLevelTeamKillAudioComponent>();
	}
};

// PythonClass PyLevelTeamKillAudioComponent.PyLevelTeamKillAudioItem
// 0x0100 (0x0138 - 0x0038)
class UPyLevelTeamKillAudioItem final : public UMarvelLevelAudioItem
{
public:
	TArray<struct FLevelAudioContent>             SelectStage;                                       // 0x0038(0x0010)(Edit, NativeAccessSpecifierPublic)
	TArray<struct FLevelAudioContent>             PrepareStage;                                      // 0x0048(0x0010)(Edit, NativeAccessSpecifierPublic)
	TArray<struct FLevelAudioContent>             RpcFightStart;                                     // 0x0058(0x0010)(Edit, NativeAccessSpecifierPublic)
	TArray<struct FLevelAudioContent>             FightStage;                                        // 0x0068(0x0010)(Edit, NativeAccessSpecifierPublic)
	TArray<struct FLevelAudioContent>             OverTimeStage;                                     // 0x0078(0x0010)(Edit, NativeAccessSpecifierPublic)
	TArray<struct FLevelAudioContent>             GameResult;                                        // 0x0088(0x0010)(Edit, NativeAccessSpecifierPublic)
	TArray<struct FLevelAudioContent>             DrawResult;                                        // 0x0098(0x0010)(Edit, NativeAccessSpecifierPublic)
	TArray<struct FLevelAudioContent>             PoisonStart;                                       // 0x00A8(0x0010)(Edit, NativeAccessSpecifierPublic)
	TArray<struct FLevelAudioContent>             PoisonMove;                                        // 0x00B8(0x0010)(Edit, NativeAccessSpecifierPublic)
	TArray<struct FLevelAudioContent>             PoisonEnd;                                         // 0x00C8(0x0010)(Edit, NativeAccessSpecifierPublic)
	TArray<struct FLevelAudioContent>             InsidePoison;                                      // 0x00D8(0x0010)(Edit, NativeAccessSpecifierPublic)
	TArray<struct FLevelAudioContent>             OutSidePoison;                                     // 0x00E8(0x0010)(Edit, NativeAccessSpecifierPublic)
	TArray<struct FLevelAudioContent>             AllyDeath;                                         // 0x00F8(0x0010)(Edit, NativeAccessSpecifierPublic)
	TArray<struct FLevelAudioContent>             EnemyDeath;                                        // 0x0108(0x0010)(Edit, NativeAccessSpecifierPublic)
	TArray<struct FLevelAudioContent>             RoundWin;                                          // 0x0118(0x0010)(Edit, NativeAccessSpecifierPublic)
	TArray<struct FLevelAudioContent>             RoundLose;                                         // 0x0128(0x0010)(Edit, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyLevelTeamKillAudioItem">();
	}
	static class UPyLevelTeamKillAudioItem* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyLevelTeamKillAudioItem>();
	}
};

}

