#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyLevelController_HeroGallery

#include "Basic.hpp"

#include "Marvel_structs.hpp"
#include "python_enums_structs.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// PythonClass PyLevelController_HeroGallery.PyLevelController_HeroDetail
// 0x03D0 (0x0860 - 0x0490)
class APyLevelController_HeroDetail : public AActor
{
public:
	bool                                          IsUseNsSmoke;                                      // 0x0490(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EHeroDetailLevelBGType                        LevelBGType;                                       // 0x0491(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_492[0x6];                                      // 0x0492(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInterface*                     LobbyCommonBGMaterial;                             // 0x0498(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FLevelSequencePlayStyle                LS_LevelBGFadeIn;                                  // 0x04A0(0x0080)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	struct FLevelSequencePlayStyle                LS_LevelBGLoop;                                    // 0x0520(0x0080)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	struct FLevelSequencePlayStyle                LS_LevelBGSwitchEffect;                            // 0x05A0(0x0080)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	struct FLevelSequencePlayStyle                LS_CommonBGFadeIn;                                 // 0x0620(0x0080)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	struct FLevelSequencePlayStyle                LS_CommonBGFadeOut;                                // 0x06A0(0x0080)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	struct FLevelSequencePlayStyle                LS_HeroBlur;                                       // 0x0720(0x0080)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	struct FLevelSequencePlayStyle                LS_ItemBlur;                                       // 0x07A0(0x0080)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	class AActor*                                 NS_HD_Smoke;                                       // 0x0820(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class AActor*                                 NS_Backdrop;                                       // 0x0828(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class APostProcessVolume*                     PostProcess_HeroDetail;                            // 0x0830(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class APostProcessVolume*                     PostProcess_HeroList;                              // 0x0838(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UMaterialParameterCollection*           MPC_Background;                                    // 0x0840(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UMaterialParameterCollection*           MPC_UIParameterCollection;                         // 0x0848(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UMaterialInterface*                     MI_Hide;                                           // 0x0850(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAkAudioEvent*                          Audio_LevelBGLoop;                                 // 0x0858(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void ReceiveBeginPlay();
	void ReceiveEndPlay(EEndPlayReason EndPlayReason);
	void ReceiveTick(float DeltaSeconds);
	void OnShowCharacterBG();
	void OnShowSkinBG();
	void LoadCharacterMI(class UObject* LevelComponentMI);
	void LoadCharacterBGMI(class UObject* LevelComponentMI);
	void LoadColorOffsetMI(class UObject* LevelComponentMI);
	void LoadCrystalMI(class UObject* LevelComponentMI);
	void LoadBackBGMI(class UObject* LevelComponentMI);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyLevelController_HeroDetail">();
	}
	static class APyLevelController_HeroDetail* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyLevelController_HeroDetail>();
	}
};

}

