#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyMantisCharacter

#include "Basic.hpp"

#include "Marvel_classes.hpp"
#include "Hero_1020_classes.hpp"
#include "PyUIController_CharacterAbilities_classes.hpp"


namespace SDK
{

// PythonClass PyMantisCharacter.PyWidget_MantisBuffMonitorItem
// 0x0000 (0x05A8 - 0x05A8)
class UPyWidget_MantisBuffMonitorItem final : public UMarvelUserWidget
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_MantisBuffMonitorItem">();
	}
	static class UPyWidget_MantisBuffMonitorItem* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_MantisBuffMonitorItem>();
	}
};

// PythonClass PyMantisCharacter.PyMantisCharacter
// 0x0020 (0x1850 - 0x1830)
class APyMantisCharacter : public AMantisCharacter
{
public:
	int32                                         HealingBuffID;                                     // 0x1830(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         BoostedBuffID;                                     // 0x1834(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(class AMarvelBaseCharacter* Target, int32 Action)> OnBuffedTeammatesUpdateDispatcher;                 // 0x1838(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyMantisCharacter">();
	}
	static class APyMantisCharacter* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyMantisCharacter>();
	}
};

// PythonClass PyMantisCharacter.PyUIController_MantisAbilities
// 0x0008 (0x0048 - 0x0040)
class UPyUIController_MantisAbilities final : public UPyUIController_CharacterAbilities
{
public:
	TSubclassOf<class UUserWidget>                BuffMonitorListClass;                              // 0x0040(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void Construct();
	void Destruct();
	void OnBuffedTeammatesUpdate(class AMarvelBaseCharacter* Target, int32 Action);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyUIController_MantisAbilities">();
	}
	static class UPyUIController_MantisAbilities* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyUIController_MantisAbilities>();
	}
};

}

