#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyModeAudioComponent

#include "Basic.hpp"

#include "Marvel_structs.hpp"
#include "MarvelLevel_classes.hpp"
#include "PyBaseAudioComponent_classes.hpp"


namespace SDK
{

// PythonClass PyModeAudioComponent.PyOwnerConditionConfig
// 0x0008 (0x0038 - 0x0030)
class UPyOwnerConditionConfig final : public UMarvelAudioCondition
{
public:
	EProcedureNotifyOwnerSide                     OwnerLimit;                                        // 0x0030(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyOwnerConditionConfig">();
	}
	static class UPyOwnerConditionConfig* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyOwnerConditionConfig>();
	}
};

// PythonClass PyModeAudioComponent.PyModeAudioComponent
// 0x0000 (0x0108 - 0x0108)
class UPyModeAudioComponent : public UPyBaseAudioComponent
{
public:
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyModeAudioComponent">();
	}
	static class UPyModeAudioComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyModeAudioComponent>();
	}
};

}

