#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PySpiderManCharacter

#include "Basic.hpp"

#include "Hero_1036_classes.hpp"


namespace SDK
{

// PythonClass PySpiderManCharacter.PySpiderManChildActor
// 0x0000 (0x0A60 - 0x0A60)
class APySpiderManChildActor final : public ASpiderManChildActor
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PySpiderManChildActor">();
	}
	static class APySpiderManChildActor* GetDefaultObj()
	{
		return GetDefaultObjImpl<APySpiderManChildActor>();
	}
};

// PythonClass PySpiderManCharacter.PySpiderManCharacter
// 0x0000 (0x1880 - 0x1880)
class APySpiderManCharacter : public ASpiderManCharacter
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PySpiderManCharacter">();
	}
	static class APySpiderManCharacter* GetDefaultObj()
	{
		return GetDefaultObjImpl<APySpiderManCharacter>();
	}
};

}

