#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyStormCharacter

#include "Basic.hpp"

#include "Hero_1015_classes.hpp"


namespace SDK
{

// PythonClass PyStormCharacter.PyStormCharacter
// 0x0000 (0x1890 - 0x1890)
class APyStormCharacter : public AStormCharacter
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyStormCharacter">();
	}
	static class APyStormCharacter* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyStormCharacter>();
	}
};

}

