#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PySummoned_LargeTentacle

#include "Basic.hpp"

#include "MarvelLevel_classes.hpp"
#include "Marvel_classes.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK
{

// PythonClass PySummoned_LargeTentacle.PyKnockUp_LargeTentacle_Attack
// 0x0000 (0x1D98 - 0x1D98)
class UPyKnockUp_LargeTentacle_Attack : public UMarvelKnockUpAbility
{
public:
	struct FVector CalcKnockUpDir();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyKnockUp_LargeTentacle_Attack">();
	}
	static class UPyKnockUp_LargeTentacle_Attack* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyKnockUp_LargeTentacle_Attack>();
	}
};

// PythonClass PySummoned_LargeTentacle.PySummoned_LargeTentacleArea
// 0x00C0 (0x0980 - 0x08C0)
class APySummoned_LargeTentacleArea final : public AMarvelLevelSummonedBase
{
public:
	uint8                                         Pad_8B8[0x8];                                      // 0x08B8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<class FString, int32>                    AreaTentacleNums;                                  // 0x08C0(0x0050)(Edit, BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
	TMap<class FString, TSet<class FString>>      TriggerBoxGroup;                                   // 0x0910(0x0050)(Edit, BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
	int32                                         TentacleSummonedID;                                // 0x0960(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          IsActive;                                          // 0x0964(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_965[0x3];                                      // 0x0965(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         TentacleBias;                                      // 0x0968(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         FloorDeathAttackScopeID;                           // 0x096C(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         CeilingDeathAttackScopeID;                         // 0x0970(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void ReceiveBeginPlay();
	void SetTentacleAreaActive(bool Inactive);
	void ReceiveTick(float DeltaSeconds);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PySummoned_LargeTentacleArea">();
	}
	static class APySummoned_LargeTentacleArea* GetDefaultObj()
	{
		return GetDefaultObjImpl<APySummoned_LargeTentacleArea>();
	}
};

// PythonClass PySummoned_LargeTentacle.PySummoned_LargeTentacle
// 0x00F0 (0x09B0 - 0x08C0)
class APySummoned_LargeTentacle final : public AMarvelLevelSummonedBase
{
public:
	uint8                                         Pad_8B8[0x8];                                      // 0x08B8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         ActiveInterval;                                    // 0x08C0(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MoveSpeed;                                         // 0x08C4(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MoveUpDelayTime;                                   // 0x08C8(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MoveUpSpeed;                                       // 0x08CC(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         KnockUpScopeID;                                    // 0x08D0(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MoveDownSpeed;                                     // 0x08D4(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         DeathMoveDownDelay;                                // 0x08D8(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_8DC[0x4];                                      // 0x08DC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<int32>                                 AttackScopeID;                                     // 0x08E0(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
	bool                                          IsRandomAttackType;                                // 0x08F0(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_8F1[0x3];                                      // 0x08F1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         AttackDelay;                                       // 0x08F4(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         AttackInterval;                                    // 0x08F8(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         RotateSpeed;                                       // 0x08FC(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         MaxAttackTimes;                                    // 0x0900(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MaxAttackTimesDelay;                               // 0x0904(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<class UAnimationAsset*>                AttackAnim;                                        // 0x0908(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, NativeAccessSpecifierPublic)
	float                                         DeathAttackDelayTime;                              // 0x0918(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         TentacleState;                                     // 0x091C(0x0004)(BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                OriginLocation;                                    // 0x0920(0x0018)(BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FVector                                TargetLocation;                                    // 0x0938(0x0018)(BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FRotator                               TargetRotation;                                    // 0x0950(0x0018)(BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	float                                         AttackTargetYaw;                                   // 0x0968(0x0004)(BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_96C[0x4];                                      // 0x096C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class USceneComponent*                        TriggerComponent;                                  // 0x0970(0x0008)(Edit, BlueprintVisible, ExportObject, BlueprintReadOnly, Net, ZeroConstructor, EditConst, InstancedReference, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class AActor*                                 MoveTarget;                                        // 0x0978(0x0008)(BlueprintVisible, Net, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         AttackID;                                          // 0x0980(0x0004)(BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_984[0x4];                                      // 0x0984(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(int32 State)>   OnStateChanged;                                    // 0x0988(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void(bool IsPreAttack)> OnPreAttackStateChanged;                           // 0x0998(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, BlueprintCallable, NativeAccessSpecifierPublic)

public:
	void ReceiveBeginPlay();
	void ReceiveTick(float DeltaSeconds);
	void OnDeath(class AController* InSource, class AActor* InSourceAvatar, const struct FAttributeModifierHandle& ParameterHandle);
	void OnRep_TentacleState();
	void MulticastAttack(int32 AttackType);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PySummoned_LargeTentacle">();
	}
	static class APySummoned_LargeTentacle* GetDefaultObj()
	{
		return GetDefaultObjImpl<APySummoned_LargeTentacle>();
	}
};

// PythonClass PySummoned_LargeTentacle.PyTraceComponent_LargeTentacle_KnockUp
// 0x0000 (0x1710 - 0x1710)
class UPyTraceComponent_LargeTentacle_KnockUp final : public UMarvelAgentTraceComponent
{
public:
	void K2_OnActivate();
	void K2_OnDeactivate();
	void OnStateChanged(int32 InState);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyTraceComponent_LargeTentacle_KnockUp">();
	}
	static class UPyTraceComponent_LargeTentacle_KnockUp* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyTraceComponent_LargeTentacle_KnockUp>();
	}
};

// PythonClass PySummoned_LargeTentacle.PyCue_Summoner_Loop_LargeTentacle
// 0x0010 (0x0ED8 - 0x0EC8)
class APyCue_Summoner_Loop_LargeTentacle final : public AMarvelCueNotify_Loop
{
public:
	class UAkAudioEvent*                          AkEvent_OnAttack;                                  // 0x0EC8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAkAudioEvent*                          AkEvent_OnAnger;                                   // 0x0ED0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void WhileActiveFX(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);
	void OnRemoveFX(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);
	void ReceiveTick(float DeltaSeconds);
	void OnPreAttackStateChanged(bool IsPreAttack);
	void OnStateChanged(int32 InState);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyCue_Summoner_Loop_LargeTentacle">();
	}
	static class APyCue_Summoner_Loop_LargeTentacle* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyCue_Summoner_Loop_LargeTentacle>();
	}
};

// PythonClass PySummoned_LargeTentacle.PyTraceComponent_LargeTentacle_Attack
// 0x0000 (0x1710 - 0x1710)
class UPyTraceComponent_LargeTentacle_Attack final : public UMarvelAgentTraceComponent
{
public:
	void K2_Initialize();
	void K2_OnDeactivate();
	void OnStateChanged(int32 InState);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyTraceComponent_LargeTentacle_Attack">();
	}
	static class UPyTraceComponent_LargeTentacle_Attack* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyTraceComponent_LargeTentacle_Attack>();
	}
};

// PythonClass PySummoned_LargeTentacle.PyCue_Scope_Loop_TentacleDeathAttack
// 0x0020 (0x0EE8 - 0x0EC8)
class APyCue_Scope_Loop_TentacleDeathAttack final : public AMarvelCueNotify_Loop
{
public:
	class UAnimationAsset*                        AttackAnimAsset;                                   // 0x0EC8(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UNiagaraSystem*                         AttackNiagara;                                     // 0x0ED0(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         NSDefaultRadius;                                   // 0x0ED8(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         SkeletalMeshDefaultRadius;                         // 0x0EDC(0x0004)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UAkAudioEvent*                          AkEvent_OnAttack;                                  // 0x0EE0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void WhileActiveFX(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);
	void OnRemoveFX(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyCue_Scope_Loop_TentacleDeathAttack">();
	}
	static class APyCue_Scope_Loop_TentacleDeathAttack* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyCue_Scope_Loop_TentacleDeathAttack>();
	}
};

}

