#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_SettingPageGamepad

#include "Basic.hpp"


namespace SDK::Params
{

// PythonFunction PyWidget_SettingPageGamepad.PyWidget_SettingyPageGamepad.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_SettingyPageGamepad_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

