#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_VoiceChatPanel

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// PythonFunction PyWidget_VoiceChatPanel.PyWidget_VoiceStateButton.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_VoiceStateButton_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// PythonFunction PyWidget_VoiceChatPanel.PyWidget_VoiceStateBase.SetMicrophoneState
// 0x0004 (0x0004 - 0x0000)
struct PyWidget_VoiceStateBase_SetMicrophoneState final
{
public:
	int32                                         MicrophoneState;                                   // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// PythonFunction PyWidget_VoiceChatPanel.PyWidget_VoiceStateBase.SetVoiceState
// 0x0004 (0x0004 - 0x0000)
struct PyWidget_VoiceStateBase_SetVoiceState final
{
public:
	int32                                         Voice;                                             // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// PythonFunction PyWidget_VoiceChatPanel.PyWidget_VoiceStateImage.SetMicrophoneState
// 0x0004 (0x0004 - 0x0000)
struct PyWidget_VoiceStateImage_SetMicrophoneState final
{
public:
	int32                                         MicrophoneState;                                   // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// PythonFunction PyWidget_VoiceChatPanel.PyWidget_VoiceStateImage.SetVoiceState
// 0x0004 (0x0004 - 0x0000)
struct PyWidget_VoiceStateImage_SetVoiceState final
{
public:
	int32                                         Voice;                                             // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// PythonFunction PyWidget_VoiceChatPanel.PyWidget_VoiceStateImage.SetIsMicrophone
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_VoiceStateImage_SetIsMicrophone final
{
public:
	bool                                          IsMicrophone;                                      // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// PythonFunction PyWidget_VoiceChatPanel.PyWidget_VoiceStateImage.SetIconColor
// 0x0010 (0x0010 - 0x0000)
struct PyWidget_VoiceStateImage_SetIconColor final
{
public:
	struct FLinearColor                           Color;                                             // 0x0000(0x0010)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// PythonFunction PyWidget_VoiceChatPanel.PyWidget_VoiceStateImage.SetMessageState
// 0x0004 (0x0004 - 0x0000)
struct PyWidget_VoiceStateImage_SetMessageState final
{
public:
	int32                                         State;                                             // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// PythonFunction PyWidget_VoiceChatPanel.PyWidget_VoiceStateImage.SetIsMessage
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_VoiceStateImage_SetIsMessage final
{
public:
	bool                                          Is_Message;                                        // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// PythonFunction PyWidget_VoiceChatPanel.PyWidget_VoiceStateImage.OnAnimationFinished
// 0x0008 (0x0008 - 0x0000)
struct PyWidget_VoiceStateImage_OnAnimationFinished final
{
public:
	const class UWidgetAnimation*                 Animation;                                         // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};

// PythonFunction PyWidget_VoiceChatPanel.PyWidget_BattleVoice_PlayerUnit.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_BattleVoice_PlayerUnit_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// PythonFunction PyWidget_VoiceChatPanel.PyWidget_CombatAudioControlPanel.OnCascadingVisibleChanged
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_CombatAudioControlPanel_OnCascadingVisibleChanged final
{
public:
	bool                                          Visible;                                           // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// PythonFunction PyWidget_VoiceChatPanel.PyWidget_CombatAudioControlEntry.OnPictureLoadCompleted
// 0x0008 (0x0008 - 0x0000)
struct PyWidget_CombatAudioControlEntry_OnPictureLoadCompleted final
{
public:
	class UTexture2D*                             Picture;                                           // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};

// PythonFunction PyWidget_VoiceChatPanel.PyWidget_VoiceStateIcon.SetMicrophoneState
// 0x0004 (0x0004 - 0x0000)
struct PyWidget_VoiceStateIcon_SetMicrophoneState final
{
public:
	int32                                         MicrophoneState;                                   // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// PythonFunction PyWidget_VoiceChatPanel.PyWidget_VoiceStateIcon.SetVoiceState
// 0x0004 (0x0004 - 0x0000)
struct PyWidget_VoiceStateIcon_SetVoiceState final
{
public:
	int32                                         Voice;                                             // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

