#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_Gallery_SeasonStory_Story

#include "Basic.hpp"

#include "PyMarvelUserWidget_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_Gallery_SeasonStory_Story.PyWidget_Gallery_SeasonStory_Story
// 0x0000 (0x05F0 - 0x05F0)
class UPyWidget_Gallery_SeasonStory_Story final : public UPyMarvelUserWidget
{
public:
	void OnInitialized();
	void Construct();
	void Destruct();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_Gallery_SeasonStory_Story">();
	}
	static class UPyWidget_Gallery_SeasonStory_Story* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_Gallery_SeasonStory_Story>();
	}
};

}

