#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SocialSetting

#include "Basic.hpp"

#include "Marvel_classes.hpp"
#include "PyDefaultUISettingEntryHandler_classes.hpp"


namespace SDK
{

// PythonClass SocialSetting.UISettingEntrySocialHandler
// 0x0000 (0x0030 - 0x0030)
class UUISettingEntrySocialHandler final : public UUISettingEntrySettingHandler
{
public:
	void BP_OnApply(class UObject* Obj, const class FString& setting_key, const TMap<class FString, class FString>& P, const TMap<int32, class FText>& OPTIONS, float Value);
	float BP_GetCurrentValue(class UObject* Obj, const class FString& setting_key, const TMap<class FString, class FString>& P, const TMap<int32, class FText>& O);
	TMap<class FString, int32> BP_OnChanged(class UObject* Obj, const class FString& setting_key, const TMap<class FString, class FString>& Params_0, const TMap<int32, class FText>& OPTIONS, float Value, const TMap<class FString, int32>& Tags);
	TMap<class FString, int32> BP_OnBtnClicked(class UObject* Obj, const class FString& setting_key, const TMap<class FString, class FString>& Params_0, const TMap<int32, class FText>& OPTIONS, float Value, const TMap<class FString, int32>& Tags);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"UISettingEntrySocialHandler">();
	}
	static class UUISettingEntrySocialHandler* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUISettingEntrySocialHandler>();
	}
};

// PythonClass SocialSetting.UISettingStreamerAnonymousOneselfHandler
// 0x0000 (0x0030 - 0x0030)
class UUISettingStreamerAnonymousOneselfHandler final : public UPyDefaultSettingEntryHandler
{
public:
	TMap<class FString, int32> BP_OnChanged(class UObject* Obj, const class FString& setting_key, const TMap<class FString, class FString>& Params_0, const TMap<int32, class FText>& OPTIONS, float Value, const TMap<class FString, int32>& Tags);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"UISettingStreamerAnonymousOneselfHandler">();
	}
	static class UUISettingStreamerAnonymousOneselfHandler* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUISettingStreamerAnonymousOneselfHandler>();
	}
};

// PythonClass SocialSetting.UISettingCrossPlatformHandler
// 0x0000 (0x0030 - 0x0030)
class UUISettingCrossPlatformHandler final : public UUISettingEntrySettingHandler
{
public:
	float BP_GetCurrentValue(class UObject* Obj, const class FString& setting_key, const TMap<class FString, class FString>& P, const TMap<int32, class FText>& O);
	TMap<class FString, int32> BP_OnChanged(class UObject* Obj, const class FString& setting_key, const TMap<class FString, class FString>& Params_0, const TMap<int32, class FText>& OPTIONS, float Value, const TMap<class FString, int32>& Tags);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"UISettingCrossPlatformHandler">();
	}
	static class UUISettingCrossPlatformHandler* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUISettingCrossPlatformHandler>();
	}
};

// PythonClass SocialSetting.UISettingAnchorModeHandler
// 0x0000 (0x0030 - 0x0030)
class UUISettingAnchorModeHandler final : public UUISettingEntrySettingHandler
{
public:
	float BP_GetCurrentValue(class UObject* Obj, const class FString& setting_key, const TMap<class FString, class FString>& P, const TMap<int32, class FText>& O);
	TMap<class FString, int32> BP_OnChanged(class UObject* Obj, const class FString& setting_key, const TMap<class FString, class FString>& Params_0, const TMap<int32, class FText>& OPTIONS, float Value, const TMap<class FString, int32>& Tags);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"UISettingAnchorModeHandler">();
	}
	static class UUISettingAnchorModeHandler* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUISettingAnchorModeHandler>();
	}
};

// PythonClass SocialSetting.UISettingAlternateNameHandler
// 0x0000 (0x0030 - 0x0030)
class UUISettingAlternateNameHandler final : public UUISettingEntrySettingHandler
{
public:
	float BP_GetCurrentValue(class UObject* Obj, const class FString& setting_key, const TMap<class FString, class FString>& P, const TMap<int32, class FText>& O);
	class FString GetOverrideEntryName(class UObject* Obj, const class FString& setting_key, const class FString& entry_name, const TMap<class FString, class FString>& P);
	TMap<class FString, int32> BP_OnBtnClicked(class UObject* Obj, const class FString& setting_key, const TMap<class FString, class FString>& Params_0, const TMap<int32, class FText>& OPTIONS, float Value, const TMap<class FString, int32>& Tags);
	TMap<class FString, int32> BP_OnStrValueChanged(class UObject* Obj, const class FString& setting_key, const TMap<class FString, class FString>& Params_0, const TMap<int32, class FText>& OPTIONS, const class FString& Value, const TMap<class FString, int32>& Tags);
	TMap<class FString, int32> BP_OnChanged(class UObject* Obj, const class FString& setting_key, const TMap<class FString, class FString>& Params_0, const TMap<int32, class FText>& OPTIONS, float Value, const TMap<class FString, int32>& Tags);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"UISettingAlternateNameHandler">();
	}
	static class UUISettingAlternateNameHandler* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUISettingAlternateNameHandler>();
	}
};

}

