#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Setting_Page_Social

#include "Basic.hpp"

#include "PyWidget_SettingPageSocial_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Setting_Page_Social.WBP_Setting_Page_Social_C
// 0x0008 (0x0608 - 0x0600)
class UWBP_Setting_Page_Social_C final : public UPyWidget_SettingyPageSocial
{
public:
	class UMarvelVerticalBox*                     VBox_Panel;                                        // 0x0600(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Setting_Page_Social_C">();
	}
	static class UWBP_Setting_Page_Social_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Setting_Page_Social_C>();
	}
};

}

