#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Setting_Control_HeroForm

#include "Basic.hpp"

#include "PyWidget_SettingBase_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Setting_Control_HeroForm.WBP_Setting_Control_HeroForm_C
// 0x0020 (0x0610 - 0x05F0)
class UWBP_Setting_Control_HeroForm_C final : public UPyWidget_SettingSelectHeroShape
{
public:
	class UMarvelImage*                           Img_HeroForm_Bg;                                   // 0x05F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Setting_Control_HeroFormBtn_C*     WBP_Setting_Control_HeroFormBtn1;                  // 0x05F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Setting_Control_HeroFormBtn_C*     WBP_Setting_Control_HeroFormBtn2;                  // 0x0600(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Setting_Control_HeroFormBtn_C*     WBP_Setting_Control_HeroFormBtn3;                  // 0x0608(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Setting_Control_HeroForm_C">();
	}
	static class UWBP_Setting_Control_HeroForm_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Setting_Control_HeroForm_C>();
	}
};

}

