#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Common_HeroPortrait

#include "Basic.hpp"

#include "PyWidget_Common_HeroHead_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Common_HeroPortrait.WBP_Common_HeroPortrait_C
// 0x0018 (0x0470 - 0x0458)
class UWBP_Common_HeroPortrait_C final : public UPyWidget_Common_HeroPortrait
{
public:
	class UWidgetAnimation*                       Anim_FadeIn;                                       // 0x0458(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UMaskHeroHeadBP_C*                      ImgMaskContent;                                    // 0x0460(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelOverlay*                         Overlay_Main;                                      // 0x0468(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Common_HeroPortrait_C">();
	}
	static class UWBP_Common_HeroPortrait_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Common_HeroPortrait_C>();
	}
};

}

