#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Squad_ConsoleOnly

#include "Basic.hpp"

#include "PyWidget_Squad_MatchPanel_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Squad_ConsoleOnly.WBP_Squad_ConsoleOnly_C
// 0x0018 (0x0608 - 0x05F0)
class UWBP_Squad_ConsoleOnly_C final : public UPyWidget_Squad_ConsoleOnly
{
public:
	class UMarvelButton*                          Btn_ConsoleOnlyMatchingRule;                       // 0x05F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelOverlay*                         Overlay_ConsoleOnly;                               // 0x05F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Squad_Check_ConsoleOnly_C*         WBP_Check_ConsoleOnly;                             // 0x0600(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Squad_ConsoleOnly_C">();
	}
	static class UWBP_Squad_ConsoleOnly_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Squad_ConsoleOnly_C>();
	}
};

}

