#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Home_Main

#include "Basic.hpp"

#include "PyWidget_LobbyHomeV3_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Home_Main.WBP_Home_Main_C
// 0x0030 (0x0658 - 0x0628)
class UWBP_Home_Main_C final : public UPyWidget_LobbyHomeV3
{
public:
	class UWidgetAnimation*                       Anim_FadeIn_EN;                                    // 0x0628(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Anim_FadeIn_CN;                                    // 0x0630(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UMarvelImage*                           Img_Marvel_Logo;                                   // 0x0638(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelCanvasPanel*                     MarvelCanvasPanel_CN;                              // 0x0640(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelCanvasPanel*                     MarvelCanvasPanel_EN;                              // 0x0648(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Home_ActivityEntrance_C*           WBP_Home_ActivityEntrance;                         // 0x0650(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Home_Main_C">();
	}
	static class UWBP_Home_Main_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Home_Main_C>();
	}
};

}

