#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WebSocketNetworking

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// Class WebSocketNetworking.WebSocketConnection
// 0x0010 (0x21A8 - 0x2198)
class UWebSocketConnection final : public UNetConnection
{
public:
	uint8                                         Pad_2198[0x10];                                    // 0x2198(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"WebSocketConnection">();
	}
	static class UWebSocketConnection* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWebSocketConnection>();
	}
};

// Class WebSocketNetworking.WebSocketNetDriver
// 0x0010 (0x0A80 - 0x0A70)
class UWebSocketNetDriver final : public UNetDriver
{
public:
	int32                                         WebSocketPort;                                     // 0x0A70(0x0004)(ZeroConstructor, Config, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_A74[0xC];                                      // 0x0A74(0x000C)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"WebSocketNetDriver">();
	}
	static class UWebSocketNetDriver* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWebSocketNetDriver>();
	}
};

}

